### PR TITLE
Update the ubuntu base image to bionic-20201119

### PR DESCRIPTION
**Pull request by VinodAnandan**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — APPROVED** [review]
Thank you, @VinodAnandan!

**Comment by Iryna-** [comment]
@diemol thank you for reviewing the change. Would that be possible to trigger a build and upload to the _dockerhub_ for this version?

**Comment by Iryna-** [comment]
sorry to disturb you again @diemol , is there any chance this version could be built and become available on DockerHub?

**Comment by diemol** [comment]
@Iryna-, sorry, I missed the previous comment.

These images were released a while ago for the Selenium 4 Grid. Maybe you are referring to the Grid 3 ones? For Grid 3 images we are keeping the changes to a minimum and only releasing new browser versions. If you have more questions, feel free to drop by our Slack/IRC channels, links can be seen [here](https://www.selenium.dev/support/).

**Comment by Iryna-** [comment]
Thank you for getting back to me @diemol (sorry, I don't have Slack). Yes, I was hoping to get this in the image for Grid v3.141.59 on DockerHub

**Comment by diemol** [comment]
No need for Slack, you can also use IRC, https://webchat.freenode.net/#selenium

We are soon upgrading to Ubuntu 20.04, I can try to update Grid 3 images as well, hopefully that works for you.

**Comment by Iryna-** [comment]
Yeah, I did try the IRC, but getting `This site can’t be reached` from where I am 😕 . That would be great if we could get Grid 3 upgraded as well if it's not too big of a hassle, thank you! 🙂

**Pull request merged**
