### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MacCracken**
just incase users are using docker-compose version 3; delineated between version 2 and 3

- [X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ddavison** [comment]
this is a nice doc update!  have you made sure that this docker compose works?

**Comment by ddavison** [comment]
I've answered my own question - it "does" work. 

one more requested change, @MacCracken - could you add the `yaml` highlighting to the code block you've specified?  Right now it will only render as preformatted text with no highlighting

**Comment by diemol** [comment]
@MacCracken please reference the variables `HUB_HOST` and `HUB_PORT` instead of `HUB_PORT_4444_TCP_ADDR` and `HUB_PORT_4444_TCP_PORT`

**Comment by diemol** [comment]
Looks good, thanks @MacCracken!

**Pull request merged**
