### PR TITLE
Update to selenium version 3.13

### PR DESCRIPTION
**Pull request by jsa34**
New release of Selenium made - update to dockerfile to reflect this.

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by diemol** [comment]
Thanks @jsa34!
Could you please double check that you have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)? I ask since the checkbox is not marked.

**Comment by diemol** [comment]
Hm, tests are not passing. Clearly it is not related to your commit, but something on the Grid might have changed and we need to update the way it is started. 
@jsa34 I can have a look in 2-3 days, but if you feel like debugging a bit, you can build the images locally and start the containers one by one and see what the problem might be.

**Comment by jsa34** [comment]
I'll take a look in a bit when I'm back at a computer... Something seems to be odd as you said with the node containers at first glance

**Comment by diemol** [comment]
@jsa34 I think that was not the real error. I think that empty string in the GeckoDriver we got in the previous run was due to the GitHub Api being over the quota, and then the curl returns nothing when the releases were queried.

I just ran the build again and we got the same errors as the first time, so the tests are failing. I will do some debugging and will let you know.

**Pull request merged**
