### PR TITLE
selenium version bump to 2.45.0

### PR DESCRIPTION
**Pull request by mgingras**
Update images to use selenium 2.45.0

### CODE REVIEW

**Comment by elgalu** [comment]
Hi! thanks! did you [sight the CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) ?

**Comment by mgingras** [comment]
Yep

Martin

**Comment by mtscout6** [comment]
@elgalu @mgingras Looks like this broke the build: https://registry.hub.docker.com/u/selenium/node-base/builds_history/85907/

**Comment by mtscout6** [comment]
The problem is that the tags have not been updated on dockerhub. I'm fixing it right now.

**Comment by mgingras** [comment]
@mtscout6 Won't the other builds need the tags updated as well?

**Comment by mtscout6** [comment]
I updated all of them :wink:

**Comment by mgingras** [comment]
:raised_hands: One step ahead. Thank you.

**Pull request merged**
