### PR TITLE
Add DBUS_SESSION_BUS_ADDRESS to env_keep (Fixes #358)

### LINKED ISSUE #358: standalone-chrome-debug hangs becouse DBUS_SESSION_BUS_ADDRESS is lost with sudo
When selenium is started via "sudo -E -i seluser" on -debug standalone, DBUS_SESSION_BUS_ADDRESS=/dev/null variable is lost and chrome hangs periodically on startup.

Just test it:
root:# docker run --rm selenium/standalone-chrome-debug env | grep DBUS
DBUS_SESSION_BUS_ADDRESS=/dev/null
root:# docker run --rm selenium/standalone-chrome-debug sudo -E -i -u seluser env | grep DBUS

Please fix this in entry_point.sh by adding "sudo -E -i seluser DBUS_SESSION_BUS_ADDRESS=/dev/null"
It's very annoying bug.

https://github.com/SeleniumHQ/docker-selenium/blob/aabd14c0b8bebdef1e492ffde927b7815ee2b19a/StandaloneDebug/entry_point.sh

### PR DESCRIPTION
**Pull request by a-k-g**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by hnryjms** [comment]
What if we change the [`ENV` line](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile.txt#L57) in the Dockerfile for Chrome to instead write the variable to Ubuntu's `/etc/environment` path? I haven't tried this in the Selenium docker machine to confirm it fixes the issue, but when running a simple `ubuntu:16.04` box (the origin of Selenium base), this diff adds environment variable changes when running `sudo -E -i -u [username] env`  as well as regular `env`

```diff
USER seluser
# Following line fixes
# https://github.com/SeleniumHQ/docker-selenium/issues/87
- ENV DBUS_SESSION_BUS_ADDRESS=/dev/null
+ RUN echo "DBUS_SESSION_BUS_ADDRESS=/dev/null" >> /etc/environment
```

**Comment by a-k-g** [comment]
That should do it as well. I don't have a preference for either approach. I can update the PR if that's a more desirable approach.

**Comment by ddavison** [comment]
is this succeeded by #386 ?  can we close this one in favor of that?

**Comment by a-k-g** [comment]
Yeah, sure.

**Pull request closed without merging**
