### PR TITLE
Add chromium (standalone) node images

### PR DESCRIPTION
**Pull request by fhoeben**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Add a chromium image, both as node and standalone node.

### Motivation and Context
This makes a chromium image available for organizations that do not want to use Google's chrome.
Furthermore it will make supporting arm64 images easier (in https://github.com/seleniumhq-community/docker-seleniarm), since chromium is supported on Linux arm64 and Chrome is not.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Thanks for the effort, but we don't want to merge this here right now. We want to merge both repos, seleniarm and this one. I don't want to maintain Chromium for x86 when people can use Chrome.

**Comment by fhoeben** [comment]
@diemol great to hear that you want merge the repos!
I want(ed) to assist with that and I actually already have a branch where I generate the cross platform images with minor changes compared to this branch (actually I don't have a separate chromium image there but I changed the chrome node to be chromium so that's probably also not the way forward). The only open issue I have there is running the tests for arm64, which I cannot get to work on GitHub actions. The tests pass on my local M1 mac, so I believe it might be fixed easily on an arm runner, which @jamesmortensen suggested could be done on Circle CI.

If you don't want a chromium image on amd64, what is your envisioned path forward merging the repos? I would say that having an image manifest containing chrome on amd64 and chromium on arm64 is not ideal either, they are not completely the same after all. And offering only arm64 chromium images seems a bit strange to me also, since chromium is available on amd64 and exactly the same build process can be used to generate the image (as this PR demonstrates).

My thought was to offer a chromium image which could be used by people that wanted cross architecture identical setups, and the edge and chrome images would remain in place being amd64 only. Then when people want to use the actual chrome that is just explicit in their image name, and switching between chrome and chromium becomes as easy as using a different image name in a setup.

I'm curious to learn how you envision the end state with both the amd64 and arm64 images.

**Comment by fhoeben** [comment]
@diemol Please see https://github.com/fhoeben/docker-seleniarm/commit/82b88b3c68730c8692c710c93a40c3cafc20067a for an example change to support building the image on arm64. I feel it is quite small. 
The amd64 GitHub actions still pass, and the tests of the chromium and firefox nodes also pass locally on my mac. I believe that building cross platform images based on that commit should not be very hard. Building the images can be done on GitHub. Testing them during CI, which is of course essential, will require arm64 based machines to run on.

I've not looked at Circle CI before, but I will try to update the config in the [docker-seleniarm](https://github.com/seleniumhq-community/docker-seleniarm) project to achieve that. Don't know whether a run will be triggered by default, I guess I will need some approval/help from @jamesmortensen before CircleCI will run based off a branch I created

**Comment by fhoeben** [comment]
It turns out I could get it to work on Circle CI on my own: https://app.circleci.com/pipelines/github/seleniumhq-community/docker-seleniarm/409/workflows/adec1d29-38f9-482a-affd-38ba879b9ccb

Needed [a small tweak](https://github.com/seleniumhq-community/docker-seleniarm/pull/57/commits/b57242d9a39622d6f1c11273af1b46d29896ce21#diff-9e40695776a7c3afc35b1bf6d31682fe8ca531271c4a883063aa428b3915387f) but now the arm images can also prove they work

**Comment by jamesmortensen** [comment]
Hi @fhoeben I just now saw this.  Thanks again for working on this.  I'll work on reviewing the files, and if everything looks good, I'll merge in and do a release.

**Comment by jamesmortensen** [comment]
Hi @fhoeben I just realized that your PR was upstream and not in docker-seleniarm.  Are you able to get your changes into docker-seleniarm?  I think you can do a force push.  If we're not able to figure out what's wrong with docker-seleniarm/trunk, we can force push to a new branch and then overlay all of the CircleCI code just like you did here.   

I made some commits to https://github.com/seleniumhq-community/docker-seleniarm/pull/57/files to attempt to do a test deploy, but I forgot your fork won't have access to upstream secrets.

**Comment by diemol** [comment]
>And offering only arm64 chromium images seems a bit strange to me also, since chromium is available on amd64 and exactly the same build process can be used to generate the image (as this PR demonstrates).

I prefer to have everything ready in the seleniarm fork and them move things here. There is an open issue about that. Regarding Chromium on amd64, I understand what you are saying, but the wide use case is to use Chrome, and this would just increase the amount of things we need to maintain, @jamesmortensen knows that pretty well.

**Comment by fhoeben** [comment]
@diemol I understand what your saying.

The PR I opened on the seleniarm fork based on this change is actually going quite well. The Circle CI build is failing on the PR, but that is just because it is missing docker hub secrets. My own branch, with my docker credentials, is now producing cross platform images based on Ubuntu (the actual docker content is identical to what is in this PR's branch)

**Comment by diemol** [comment]
OK, I will close this PR and have a look to that one.

**Pull request closed without merging**
