### PR TITLE
feat: video recording with pluggable upload container

### PR DESCRIPTION
**Pull request by msvticket**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

This PR adds support for 2 sidecars to the browser nodes that

1. Record video using the selenium video image
2. Upload the recorded video

This PR is inspired by #1715, but having a separate container for upload makes it possible to support new upload mechanisms without having to change the video image.

Another difference from #1715 is that the sidecars exit when the browser node exists, making them suitable for jobs and not only deployments.

### Motivation and Context

While an image for video recording is available no support is available for Kubernetes through in the helm chart.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by win5923** [comment]
Can this feature be used on https://jenkins-x-charts.github.io/repo ?

**Review by diemol — CHANGES_REQUESTED** [review]
This looks good, and is very similar to the idea I had, to use sidecars. What I was not able to point out is how do we stop the video container before the upload? The process needs to be stopped gracefully to avoid corrupting the video.

**Comment by msvticket** [comment]
> This looks good, and is very similar to the idea I had, to use sidecars. What I was not able to point out is how do we stop the video container before the upload? The process needs to be stopped gracefully to avoid corrupting the video.

Here
https://github.com/SeleniumHQ/docker-selenium/blob/aba2fc1d09b7086d22f478e63516e3615d477855/charts/selenium-grid/templates/video-cm.yaml#L71-L75

So when a recording is in progress, but the selenium node isn't reporting any session is in progress a signal is sent to ffmpeg to stop recording (`kill`) and then the script waits for ffmpeg to finish (`fg`).

**Comment by qalinn** [comment]
Hello Guys,
@diemol any news on this topic?
@msvticket  do you need any help to develop, to test?
Thank you!

**Comment by diemol** [comment]
I thought this was still on draft and you were working on it @msvticket. Can you please fix the conflicts and then I can review it.

**Comment by msvticket** [comment]
> I thought this was still on draft and you were working on it @msvticket. Can you please fix the conflicts and then I can review it.

And I were waiting for comments from you ;-)
How about I resolve the conflicts and then you take another look?

**Comment by subin-krishna-test** [comment]
@msvticket 
Any configuration to upload only the videos required. 
Thanks in advance.

**Review by diemol — APPROVED** [review]
Thank you, @msvticket!

**Pull request merged**
