### PR TITLE
chart(feat): add graphql metrics exporter for monitoring

### PR DESCRIPTION
**Pull request by VietND96**
### **User description**

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context
- Add a GraphQL exporter listen on Grid GraphQL endpoint
- Add additional scrape config for Prometheus to scrape metrics from the GraphQL exporter

Metrics on Prometheus start with prefix `query_` and following is graphql schema. It looks like

image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Added a GraphQL metrics exporter for monitoring Selenium Grid.
- Updated Selenium test setup to conditionally add browser options.
- Enhanced Kubernetes templates with monitoring exporter configurations.
- Updated Go version and Docker base image for improved compatibility.
- Added documentation and badges to README for better visibility.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>chart_setup_env.sh</strong><dd><code>Update Go version in chart setup script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/charts/make/chart_setup_env.sh

- Updated Go version from 1.22.3 to 1.23.2.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-c30ef0620922a867b3cc6b774127ee5898120d40ca2831ab98d2e5036ac510c9">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_helpers.tpl</strong><dd><code>Add GraphQL URL for monitoring exporter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/_helpers.tpl

- Added GraphQL URL definition for internal monitoring exporter.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-a57e8d3d1ad8ed854bf7e00ac004560f3dfe6d1178d5c5d45e455f8eaeb53361">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_nameHelpers.tpl</strong><dd><code>Define fullname for Selenium metrics exporter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/_nameHelpers.tpl

- Defined fullname for Selenium metrics exporter.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-81a82f068405c6e0c78f9c712e58508ee92d328bcd4329cfdb7f7c3b25c11282">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Add executable permission for websockify script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

NodeBase/Dockerfile

- Added executable permission for websockify run script.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-16a06916a1ac13cfa86d64f9a62439648853b0e48f98b68ac36305f31de7f2c4">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>selenium-grid.yaml</strong><dd><code>Add scrape configuration for Selenium Grid analytics</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/scrape/selenium-grid.yaml

- Added scrape configuration for Selenium Grid analytics.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-fefba64de8701f1cf4703f9c8b2a7675f853f5f9e5cbbe4766c30ce26f8b0e90">+15/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>monitoring-exporter-deployment.yaml</strong><dd><code>Add deployment template for monitoring exporter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/monitoring-exporter-deployment.yaml

- Added deployment template for monitoring exporter.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-afed9207bebc6aec4509b0bd0b06a03357ced6e8df842f25a6bb1bda7838a8d3">+35/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>monitoring-exporter-service.yaml</strong><dd><code>Add service template for monitoring exporter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/monitoring-exporter-service.yaml

- Added service template for monitoring exporter.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-02f6b0f77746e70c1dc846af4ce9dd4b1e9780cfb4a20363a1705e58fab9cdd5">+27/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>monitoring-scape-secret.yaml</strong><dd><code>Add secret template for monitoring scrape configuration</code>&nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/monitoring-scape-secret.yaml

- Added secret template for monitoring scrape configuration.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-e92939a4c8c61d4a895b36242798dcf072afb402c2f4225efdd6852f96a807a6">+29/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>patch-keda-objects-job.yaml</strong><dd><code>Update KEDA patch job for TriggerAuthentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml

- Updated KEDA patch job to include TriggerAuthentication.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-45939f6d4fb5ad9a484c9afd9221bf408cf9e2c0afa2a5198cdfdb4a2d937a24">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>trigger-auth.yaml</strong><dd><code>Add labels to trigger authentication template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/trigger-auth.yaml

- Added labels to trigger authentication template.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-d63b3e0bedc65da71523e1e16275b75d1f202fc50bc3b2ff1b2a11333824700f">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Enhance browser options setup in Selenium tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/SeleniumTests/__init__.py

<li>Conditional addition of Chrome and Edge options for disabling <br>features.<br> <li> Added Firefox options for enabling downloads.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-9e40695776a7c3afc35b1bf6d31682fe8ca531271c4a883063aa428b3915387f">+9/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Update base image version in Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Base/Dockerfile

<li>Updated base image from ubuntu:noble-20240827.1 to <br>ubuntu:noble-20240904.1.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-c7235ebbda8248c044e6b13da481ae97f4a21846ed2341a056b6b873abaa482b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Makefile</strong><dd><code>Update KEDA based tag version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Makefile

- Updated KEDA based tag version.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Add release downloads badge to README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

README.md

- Added badge for release downloads.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>CONFIGURATION.md</strong><dd><code>Update configuration for monitoring and RBAC roles</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/CONFIGURATION.md

<li>Updated RBAC role settings for KEDA resources.<br> <li> Added configuration for monitoring exporter.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2425/files#diff-8f21b9acf6691fc99d88780146e016715fe83ed0b5ef37fe81455f892d347786">+18/-2</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by VietND96** [comment]
Now, few GraphQL data is scraped to Prometheus. @Doofus100500, do you think a standard Grafana dashboard can be created (export as json, put in chart resources) and imported while installing chart?

**Comment by Doofus100500** [comment]
@VietND96 I think everything should work out. During the Grafana deployment, you need to set sidecar.dashboards.enabled to true and add a ConfigMap with json to your chart with label: grafana_dashboard
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L970

**Comment by VietND96** [comment]
Yes, I see. However, I am referring on what chart items, metrics we will visualize on a standard Dashboard that we will deliver.

**Comment by Doofus100500** [comment]
Then I’ll just show mine.
image
image
image
image
And the last one is about queue

**Comment by yagni92** [comment]
@Doofus100500 would you mind sharing the queries as well, please?

**Comment by Doofus100500** [comment]
@yonigolob1 
```
$serverInfoRequest = 'query { 
    grid { 
        uri, nodeCount, maxSession, sessionCount, version, sessionQueueSize 
    } 
}'

$sessionsInfoRequest = 'query {
    sessionsInfo {
        sessions {
            id,
            capabilities,
            startTime,
            uri,
            nodeId,
            nodeUri,
            sessionDurationMillis,
            slot { id, stereotype, lastStarted }
        }
    }
}'

$sessionsInQueueInfoRequest = 'query {
    sessionsInfo {
        sessionQueueRequests
    }
}'

$nodesInfoRequest = 'query {
    nodesInfo {
        nodes {
            id,
            uri,
            status,
            maxSession,
            slotCount,
            sessions {
                id,
                capabilities,
                startTime,
                uri,
                nodeId,
                nodeUri,
                sessionDurationMillis,
                slot {
                    id,
                    stereotype,
                    lastStarted
                }
            },
            sessionCount,
            stereotypes,
            version,
            osInfo {
                arch,
                name,
                version
            }
        }
    }
}'
```

**Comment by yagni92** [comment]
@Doofus100500 sorry my bad. I meant to the promql queries in the attached screenshots

**Comment by Doofus100500** [comment]
We write metrics to Graphite

**Comment by yagni92** [comment]
> We write metrics to Graphite

Gotcha. Thanks anyway

**Pull request merged**
