### PR TITLE
K8s deployment

### PR DESCRIPTION
**Pull request by sahajamit**
### Description
Added the yaml configuration file to deploy the grid 4 alpha release docker images inside a kubernetes environment.

### Motivation and Context
I have been using the selenium 4 grid alpha release in my local kubernetes environment and for this purpose I have created the complete deployment yaml to deploy the full grid in k8s environment.

As I could only see the docker-compose yaml file in this repo so I have decided to contribute the kubernetes yaml to this repository so that others can also start using it.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thanks, @sahajamit! This is great!

Could you please add some instructions to the readme, showing how to use it?

**Comment by sahajamit** [comment]
@diemol, I have added the documentation in readme.

**Comment by sahajamit** [comment]
@diemol: Can you please help merging this PR ?

**Comment by diemol** [comment]
@sahajamit I haven't had time to test it.
A way to help me test it would be to add a GitHub action that starts minikube and uses this k8s configuration to start the Grid and run a couple of tests.

**Comment by sahajamit** [comment]
@diemol : Sure let me setup a Github action and will revert back in couple of days.

**Comment by sahajamit** [comment]
@diemol : I have added a github action which will spin up a minikube cluster, deploy the grid4 and also do a simple smoke test. Pls let me know if any other test needs to be added.

**Review by diemol — APPROVED** [review]
Thank you, @sahajamit! This is great 🎉

**Pull request merged**
