### PR TITLE
Added 'custom' property to node config.

### PR DESCRIPTION
**Pull request by UlianaHolub**
Original node config json can contain 'custom' property, but current 'generate_config' files do not support it.

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Added 'custom' property to node config.

### Motivation and Context

Original node config json can contain 'custom' property, but current 'generate_config' files do not support it.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Thank you for this, @UlianaHolub!

I need a few days to test this locally because the Travis integration does not work anymore. After that I can merge and do a release.

**Review by diemol — APPROVED** [review]
Thank you, @UlianaHolub!
Congrats on your first contribution!

**Comment by isaacbowen** [comment]
Not sure if this is the right place to report this, _but_ the first release that had this PR ([3.141.59-20210729](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210729)) started giving us service timeouts (using selenium-webdriver). Rolling back to [3.141.59-20210713](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210713) clears those up.

**Comment by diemol** [comment]
This commit is not related to the issue, it is a problem in Chrome 92.

There is an issue pinned on the issues tab, please have a look, a workaround is mentioned there.

**Comment by isaacbowen** [comment]
Thanks @diemol! :) Appreciate it.

**Pull request merged**
