### PR TITLE
Added openssh-client (scp support)

### PR DESCRIPTION
**Pull request by wildloop**
What about adding these developer tools to containers:
- tcpdump - to debugging TCP connections
- mc - visual file manager
- spc - to transfer files
?

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by diemol** [comment]
Hi @wildloop,

Not sure, maybe it is a good idea. But before deciding:
- Do you know how much space are the images using by adding those packages?
- What are the use cases for this packages? So we understand if it makes sense to add them in the images or if it is better just to add guidelines on how to add them in case people want to use them.

In addition, this is (I think) the first time this is suggested, so not sure if this is a common use case. In general, we prefer to have the images as simple as possible, without packages that are not needed for normal test execution (as people mostly use the images in CI pipelines where those tools would not make a difference). Maybe a good WiKi showing how to do this is better.

What do you think?

**Comment by diemol** [comment]
I don't mean to be annoying or something like that, but we would like to understand better the need of including these packages...

>What are the use cases for this packages? So we understand if it makes sense to add them in the images or if it is better just to add guidelines on how to add them in case people want to use them.

In addition, if after checking your reply, we add the package, we also need docs explaining why the package is there, its use cases and examples. Would be cool to have those in the PR as well.

**Comment by wildloop** [comment]
`openssh-client` is required to connect to this containers using the SCP protocol, for example to copy log file using WinSCP.

**Comment by diemol** [comment]
Can't you do the same with `docker cp`?
If you want to go inside the container, you can also just do `docker exec -it <containerName> bash`, right?

**Comment by wildloop** [comment]
You're right.
Everything can be done with a hammer, but it is sometimes more convenient to use pliers - so SCP vs 4MB?

**Comment by barancev** [comment]
Sorry, I too can't see why `scp` is better than `docker cp`. It's not about size, it's other sort of economy.

**Comment by wildloop** [comment]
Because docker cp is not a protocol that can work with [WinSCP](https://winscp.net) :)

**Comment by barancev** [comment]
And why should we care about WinSCP?

**Comment by barancev** [comment]
By the way, to be able to use WinSCP we should add to container an ssh server, not scp (that is a client), right?

**Comment by wildloop** [comment]
To use SCP protocol the scp binary has to be present on the server - `apt install openssh-client`.
SCP is convenience because there are a lot of SCP clients: AbsoluteTelnet, Dropbear, lsh, OpenSSH, PACManager, PuTTY, SecureCRT, SmartFTP, Tera Term, WinSCP, Xshell, ZOC.

Please feel free to close this PR :)

**Pull request closed without merging**
