### PR TITLE
point shielding in README

### PR DESCRIPTION
**Pull request by Doofus100500**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by VietND96** [comment]
@Doofus100500, thank you for your looking into chart README!

**Comment by VietND96** [comment]
@Doofus100500, btw, did you try the RCLONE configs in the chart? Is it easy and flexible?

**Comment by Doofus100500** [comment]
@vietnd96 Yes, everything is great! I'm passing the config using --set-file by substituting a GitLab variable of file type.

**Comment by Nagam-Naidu** [comment]
@Doofus100500 Need your help related to https://github.com/SeleniumHQ/docker-selenium/issues/2320 ticket which you have raised.

Wanted to know how did you resolve it. We are also using Selenium grid kubernetes setup for running playwright tests.

Although after running tests on the new setup it is working fine with selenium tests but it is failing for playwright tests. Below is the config yaml we are using for chrome node. Can you help us solve this as i see your comment that is it working fine.
Sorry to tag you here as i was not allowed to comment on the resolved ticket. 

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # volumes:
      # - name: dshm
      #   emptyDir:
      #     medium: Memory
      #     sizeLimit: 2Gi
      containers:
      - name: {{ .Release.Name }}
        image: selenium/node-chrome:4.22.0-20240621
        ports:
          - containerPort: 5555
          - containerPort: 5900 #vnc port
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_NODE_SESSION_TIMEOUT
            value: "1200"
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: "600"
          - name: JAVA_OPTS
            value: "-Dwebdriver.chrome.whitelistedIps="
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
          - name: SE_NODE_GRID_URL
            value: https://selenium-dc.deepintent.com/
          - name: SE_NODE_PORT
            value: "5555"
          - name: SE_START_VNC
            value: "True"
          - name: SE_START_XVFB
            value: "False"
          - name: NODE_MAX_SESSION
            value: "1"
          # - name: SE_NODE_HOST
          #   value: "0.0.0.0"
          # - name: SCREEN_WIDTH
          #   value: "1920"
          # - name: SCREEN_HEIGHT
          #   value: "1024"
          - name: SE_VNC_NO_PASSWORD
            value: "1"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "2"
          - name: JAVA_OPTS
            value: "-Djdk.httpclient.websocket.intermediateBufferSize=3000000 -Dwebdriver.chrome.whitelistedIps="
          - name: SE_OPTS
            value: "--log-level FINE"
          - name: SELENIUM_LOG_LEVEL
            value: "ERROR"
          - name: CHROME_OPTS
            value: "--no-sandbox --disable-dev-shm-usage --headless"
        # volumeMounts:
        #   - mountPath: /dev/shm
        #     name: dshm
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1000m"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
    - name: nodeport
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: node-port-grid
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: vnc-port
      protocol: TCP
      port: 5900
      targetPort: 5900
  selector:
    app: {{ .Release.Name }}`

**Comment by Doofus100500** [comment]
@Nagam-Naidu Hello, why not use standard pods with Chrome (from the chart), and for scaling enable KEDA? Everything should work fine with them. But if you really need your own, you can look at how the standard ones are deployed and do it similarly.

**Pull request merged**
