### PR TITLE
test(chart): Parallel tests execution against autoscaling in Kubernetes

### LINKED ISSUE #1975: Helm Charts maintainer needed
### Feature and motivation

We have been unable to handle updates and proper testing for the helm chart. We are looking for someone who wants to maintain them long-term.

### Usage example

If we do not find someone by the end of November 2023, we will move the chart to the https://github.com/seleniumhq-community organization.

### PR DESCRIPTION
**Pull request by VietND96**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
test(chart): Parallel tests execution against autoscaling in Kubernetes

### Motivation and Context
Reuse existing sanity tests within the implementation of the concurrent executor to test the feature Selenium Grid Autoscaling on Kubernetes using KEDA.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
My concern is... what do we do when it fails? How do we know what needs to be done if it fails?

**Comment by VietND96** [comment]
You mean how do we know what needs to be done for the test failed or the fix needed for grid or chart?

**Comment by diemol** [comment]
> You mean how do we know what needs to be done for the test failed or the fix needed for grid or chart?

Exactly. Since this is testing an external dependency (keda).

**Comment by VietND96** [comment]
Yes, when I was adding this, I thought to guarantee regression issue only. For example use cases
- Someone raises PR to bump the default KEDA version used in chart.
- Someone raises PR to improve the chart template related to feat autoscaling

If this test failed...the author should rework it.

**Review by diemol — APPROVED** [review]
Let's add it then. If it gets unstable we need to analyze how much time we are investing in it. 

Thanks, @vietnd96!

**Comment by VietND96** [comment]
Thank you! I will merge this.

**Pull request merged**
