### PR TITLE
1335: video_ready_port should be an int

### PR DESCRIPTION
**Pull request by therealdjryan**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

When setting VIDEO_READY_PORT `environ.get()` returns a string but an int is required
### Description

wrap `int(environ.get('VIDEO_READY_PORT', 9000))` in an `int()
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by therealdjryan** [comment]
Relates to https://github.com/SeleniumHQ/docker-selenium/issues/1335

**Review by diemol — COMMENTED** [review]
Thank you for this PR, could you please sign the CLA so we can merge?

**Comment by therealdjryan** [comment]
Hi @diemol , 
CLA Signed

**Review by diemol — APPROVED** [review]
Thank you!

**Pull request merged**
