### PR TITLE
Firefox crash for version lower than 52

### PR DESCRIPTION
**Pull request by jackTheRipper**
Hi,

This PR fix the following issues with Firefox:
 - https://github.com/SeleniumHQ/docker-selenium/issues/397
 - https://github.com/SeleniumHQ/docker-selenium/issues/415

The fix adds the required dependencies for the Firefox versions lower than 52 and make it stable again.

- [ X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ddavison** [comment]
will updating the version to 52 fix this?  if so, then [we're all good now](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefox/Dockerfile#L13)

**Comment by jackTheRipper** [comment]
Updating to the 52 doesn't solve issue. I want to run my tests against different version of Firefox.

Just updating the version without that `if` wouldn't the issue. 

If you take a look at both of the issues I mentioned the problem comes from some missing dependencies.

I have tested both version on my side (52, 51.0.1). Without the packages I added to the image the 51.0.1 crash. The 52 as you say doesn't have the issue. 

I am using currently the version '3.1.0-astatine'.

Maybe the PR shouldn't go to master but to that specific branch?

**Comment by jackTheRipper** [comment]
@ddavison question unrelated to my PR: instead of having a Selenium base installing both Java dependencies and Selenium, wouldn't it be easier to have a base Docker image which setups Java and a Docker image which setups Selenium?

**Comment by jackTheRipper** [comment]
I performed some tests available in this [gist](https://gist.github.com/jackTheRipper/af09b57f7308b6f0c9983ed19615405c)

It compares the current image without my modifications to the one with my modifications for the version 51.0.1.

**Comment by jackTheRipper** [comment]
@ddavison any news regarding the PR?

**Comment by brandomr** [comment]
@jackTheRipper still getting weird timeouts/tab crashes even using this PR

**Comment by jackTheRipper** [comment]
@bandomr: are you using http basic authentication for your tests?

**Comment by brandomr** [comment]
@jackTheRipper no, I'm just running grid/node-firefox against some sites that don't require auth

**Comment by jackTheRipper** [comment]
@brandomr: could you provide some logs?

**Comment by brandomr** [comment]
I'm seeing:

```
[Parent 160] WARNING: pipe error (56): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 160] WARNING: pipe error (49): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Parent 160] WARNING: pipe error (46): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```

and then:
```
02:06:31.889 INFO - Session f47c7085-5135-4792-9714-874cf9147084 deleted due to client timeout
1491357991893	Marionette	INFO	New connections will no longer be accepted
```

**Comment by jackTheRipper** [comment]
Yes I had the same messages.

@brandomr could you re use the example I shared in my gist and provide the whole logs? 

I need to see which capabilities you are using. 

Are you running the tests  against Firefox 51.0.1 or lower?

**Comment by brandomr** [comment]
@jackTheRipper no I was using the default (FF 52+). I'll downgrade and try to get you full logs. Thanks for the help with this stuff

**Comment by jackTheRipper** [comment]
@brandomr after re reading your comments it's not related to my PR. 
You are talking about a version of Firefox up to 52. My PR is here for fixing an issue for the version lower than 52.

In your case I think that your issue is related to the geckodriver

**Comment by jackTheRipper** [comment]
@ddavison What is the status about the pull-request?

**Comment by ddavison** [comment]
well, can't do much until the conflicts have been resolved :)  but i'd like some other people's opinion on the matter.  

@beyondevil ?
@tparikka ?

**Comment by jackTheRipper** [comment]
@ddavison sorry for not fixing it earlier. Here it is.

**Comment by BeyondEvil** [comment]
Some quick thoughts.

General:
If you change the FF version (ie. rebuild the image(s)) you can add the missing library (libasound 2) at that point. As we kind of expect at that point that you know what you're doing.

Specific:
Not sure you need anything else than the libasound 2 library, as I fail to see how this solves the other issue (instability). If that is the case, skip the `if` and just install libasound 2 regardless as there are a number of "unused" libraries installed anyway. libasound 2 is fairly lightweight and won't bloat the image by much. But I could definitely be in the wrong here. Interesting to see if others with this issue finds the solution in this PR.

My 0.2 anyway. 
@ddavison 
This is kind of what we talked about with trying to make the images more versatile and not locked to specific combinations of browser/driver/selenium versions. I should have some time next week (not this coming one) to start looking at a solution for that. But I want us to discuss testing first. Maybe set up a meeting for the coming week?

**Comment by navels** [comment]
bump

**Comment by diemol** [comment]
Hi all,

I agree with @BeyondEvil's last comment, but the main question for me is if this was still an issue... 
I am not sure how many people are still testing with a Firefox version lower than 52. I am sure there are, but I guess this is not the common case. 
What do you think?

**Comment by diemol** [comment]
I'll close this PR since we didn't get more feedback. We can take a look at it in case it makes sense to treat this case in the images.

**Pull request closed without merging**
