### PR TITLE
Upgrade Selenium to version 2.50.1.

### PR DESCRIPTION
**Pull request by kayabendroth**

### CODE REVIEW

**Comment by sethuster** [comment]
Please Merge This.

**Comment by AdamAJeng** [comment]
+1

**Comment by spyl94** [comment]
:+1:

**Comment by jbalbien** [comment]
+1

**Comment by sethuster** [comment]
Why did this take so long?

**Comment by dylanlive** [comment]
Does anyone know when this usually takes effect on the Docker Hub?

https://hub.docker.com/r/selenium/hub/tags/ is only listing 2.50.0, which apparently was updated 42 minutes ago?

**Comment by kayabendroth** [comment]
@sethuster Sorry for the delay.

**Comment by kayabendroth** [comment]
@dylanlive Some tags are missing. Will look into it tomorrow.

**Comment by kayabendroth** [comment]
@rubytester The images in the Docker Registry (https://hub.docker.com/r/selenium) do not have the latest tags (2.50.1 and 2.52.0). Does someone need to add those somewhere?

When looking at one of the failing build pages (https://hub.docker.com/r/selenium/hub/builds/bffcvg7bqgeuh8ndh7rvjfq/) it says: ```Build failed: Tag 2.52.0 not found in repository docker.io/selenium/base```.

**Pull request merged**
