### PR TITLE
feat: Update Video/Dockerfile with based image ffmpeg:6.0-alpine

### PR DESCRIPTION
**Pull request by VietND96**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Update based image to [jrottenberg/ffmpeg:6.0-alpine](https://hub.docker.com/layers/jrottenberg/ffmpeg/6.0-alpine/images/sha256-ea1e3fe129de112b890bcb08fc0795cec29d63cd3b194eb46a2e55adc785e274)

### Motivation and Context
- Update ffmpeg version from 4.3.1 to 6.0
- Update based OS from Ubuntu20.04 to Alpine3.13, the size of image gets reduced from 377MB to 263MB (all the same dependencies are installed to ensure supervisord and shell scripts can be run properly)
- Dependencies curl, jp are added to capture and extract sessionId for file name when using it in Autoscaling Selenium Grid in Kubernetes (motivated by #1881)
- I have already tested the video image is built on top of this change [ndviet/video:ffmpeg-6.0-20231025](https://hub.docker.com/layers/ndviet/video/ffmpeg-6.0-20231025/images/sha256-de885fb09519360fb3b9b09f811c81da5b48c6f428a8e31f4b767136085cf6c0) with [docker-compose-v3-video.yml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml) and [Autoscaling Selenium Grid in Kubernetes](https://github.com/ndviet/test-scaling-grid?tab=readme-ov-file#heavy_check_mark-231025). It works fine.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Oh, I merged #1881, which causes conflicts here. Could you please solve them so I can merge?

**Comment by VietND96** [comment]
Ok, let me resolve conflicts and retest after #1881

**Comment by VietND96** [comment]
Hi @diemol ,
I already resolved conflicts. I also built locally the chart after #1881 and tested it with the image in part of this PR. It works fine.
Kindly review and feedback. Thanks!

**Review by diemol — APPROVED** [review]
Thank you, @vietnd96!

**Pull request merged**
