### PR TITLE
Start from a random number when xvfb looks for available display (#785)

### PR DESCRIPTION
**Pull request by anto-ac**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ddavison** [comment]
instead of generating a random server number, can we just use [--auto-servernum](http://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html) ?

>  Try to get a free server number, starting at 99, or the argument to --server-num.

this would save us from maintaining another shell file that gets copied into all containers.

**Comment by anto-ac** [comment]
We’re doing that already. It was introduced my previous PR. -a is equivalent to —auto-servernum.

We thought there could be a race condition with some conflict in the usage of the same port on different containers.

Overall we’re unsure as to why this is happening. If someone had any idea, perhaps some deeper knowledge about how xvfb works, it would be really appreciated.

**Comment by anto-ac** [comment]
As you posted above, the -a options works this way:

-a --auto-servernum          
try to get a free server number, starting at --server-num

So they can be used together. You ask xvfb-run to pick an available server number using -a and you specify from which number it should start from using —server-num. If you don’t specify it, it would start from 99.

The idea behind the change is that by starting to look for a server number from a random number, the likelihood of a race condition would be much lower.

Sadly though, this change does not fix the issue itself. So while the change is harmless, it’s probably unnecessary.

It is really annoying because it makes our builds flakey.

**Comment by diemol** [comment]
I'll close this PR since we saw that this does not fix the issue in your environment. We need to find out what is happening to the displays when it runs on Ubuntu.

**Pull request closed without merging**
