### PR TITLE
Generate hub config from runtime environment.

### PR DESCRIPTION
**Pull request by phensley**
This allows overriding some of the hub's config properties at startup time using environment variables.  If there is interest I can implement this for the nodes as well.

### CODE REVIEW

**Comment by mtscout6** [comment]
I like this! Just need that minor cleanup issue taken care of.

**Comment by mtscout6** [comment]
Actually, could you also update the README to explain to others how to use this?

**Comment by willroden** [comment]
I like this.  The fewer hardcoded values the better.

**Comment by phensley** [comment]
Ok I've updated the commit with the needed traps and added a note in the hub's README

**Comment by mtscout6** [comment]
@phensley One last housekeeping issue, Have you [signed the CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) yet?

**Comment by phensley** [comment]
@mtscout6 Yep I signed the CLA before submitting this PR! :+1:

**Comment by mtscout6** [comment]
Closed by commit 778659f

**Pull request closed without merging**
