### PR TITLE
fixed cmd to entrypoint

### PR DESCRIPTION
**Pull request by rishav887**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Typo CMD instead of EntryPoint for executable

### Motivation and Context
The executable wont work

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — COMMENTED** [review]
Why is this needed?

**Comment by rishav887** [comment]
Preventing from being overridden at runtime and will make sure sh runs and is not optinal as incase of CMD

**Comment by jamesmortensen** [comment]
Hi @rishav887 Thanks for digging in to help out.  At this point, I prefer having CMD instead of ENTRYPOINT.  Here is why:

Having container images using CMD instead of ENTRYPOINT makes it much easier to troubleshoot, triage, and maintain these images.  I oftentimes start containers using just "bash" just so I can dig inside the container to investigate an issue.  Additionally, there may be other frameworks which are built on top of docker-selenium which may be impacted by this change, and I've experimented with building a few things on top of docker-selenium before where I've needed to override CMD.

Based on these experiences, I'm not sure I support this change with the current knowledge I have about how CMD and ENTRYPOINT works.  Is there something I'm still missing?  Could you help us understand the motivation for wanting to prevent this behavior?  Thank you.

**Comment by diemol** [comment]
Thank you for chiming in, @jamesmortensen! 

@rishav887, I will close this PR for the detailed reasons given above. If you still want to contribute, please check the open issues or join our Slack channel (https://www.selenium.dev/support/)

**Pull request closed without merging**
