### PR TITLE
Upgrade to Selenium version 2.46.0.

### PR DESCRIPTION
**Pull request by kayabendroth-epages**

### CODE REVIEW

**Comment by gongo** [comment]
:+1:

**Comment by rubytester** [comment]
I am prepping the branch naming and docker hub build tags for 2.46.0

**Comment by rubytester** [comment]
Some housekeeping @kayabendroth-epages Have you signed the CLA as described in CONTRIBUTING.md? If not, please sign it and indicate in this pull request. 
Thank you.

**Comment by mtscout6** [comment]
Some folks on IRC are asking about this, was node-firefox missed: https://registry.hub.docker.com/u/selenium/node-firefox/tags/manage/

**Comment by rubytester** [comment]
Ooops. I missed it. fixed

- General setup: I setup all Automated Build on docker hub to build on branch names so as we move forward we advance the branch: master branch builds `latest` and 2.46.0 branch builds `2.46.0` image.

- The Issue: I am finding with docker hub Automated Build triggers they don't run in predictable sequence as we need them: First build base, then (hub and node-base) then (node firefox and chrome) and so on. ([this produces errors like this](https://registry.hub.docker.com/u/selenium/node-base/build_id/26416/code/bwrh8yczsuyqjllha7mvbxh/))

  - I am not sure if there is a 'sequence' trigger builder I can apply so we always build 'base' first and then it should trigger downstream builds.

**Pull request merged**
