### PR TITLE
Modified make build process to use --build-arg instead of generate.sh scripts, eliminating the templates.

### LINKED ISSUE #1649: [🚀 Feature]: Using --build-arg to substitute the IMAGE_TAG name instead of generating copies of Dockerfiles during the build process.
### Feature and motivation

Based on a conversation with @AutomationD and diemol, we now know container Dockerfiles have the ability to substitute values in the FROM block with arguments passed in as `--build-arg`.  Currently, we are generating Dockerfiles from Dockerfile.txt files and replacing templated values with real ones using a shell script.  

Instead, we can simplify this process using `docker build --build-arg $IMAGE_TAG`, which then allows us to:

- eliminate the generate.sh scripts
- Remove Dockerfiles from all except the Base folder.
- Rename Dockerfile.txt to Dockerfile in all folders except Base.

This will reduce the complexity of the build process and reduce code conflicts between forks, since the Dockerfile only changes if it needs logical updates made to it (instead of generated changes).

This issue would also involve changes to the Makefile to remove references to invocations of generate.sh and to also add in the --build-arg IMAGE_TAG to every docker build command. 

### Usage example

`IMAGE_TAG=4.3.0-20220726 docker build -t selenium/standalone-chrome:${IMAGE_TAG} --build-arg=${IMAGE_TAG} .`

The above build command would use `FROM selenium/node-chrome:4.3.0-20220726` without needing to modify the Dockerfile or generating a Dockerfile using code.

### PR DESCRIPTION
**Pull request by jamesmortensen**
This PR takes advantage of the dynamic image feature where we pass in the namespace, version, authors, and in some instances, the base image to be used as the FROM argument, and fixes #1649 

### Description

- Modified all Dockerfiles to use --build-arg to pass in namespace, version, authors, and in the case of standalone browser images, the base image.
- Removed Dockerfile.txt files, which are no longer needed.
- Removed generate.sh scripts, which are no longer needed.
- Removed the "auto-generated" warnings from all of the Dockerfiles.
- Removed the StandaloneChrome, StandaloneFirefox, StandaloneEdge folders as these images can all be built from the Standalone folder.
- Modified Makefile:  Removed all generate_x commands and added --build-args to the docker build commands via a common Makefile variable FROM_IMAGE_ARGS

### Motivation and Context

This reduces the amount of files needed for the build process, and it simplifies the lines of code in the Makefile. It also eliminates commits to auto-generated files, which also eliminates unneeded conflicts when syncing forks.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jamesmortensen** [comment]
I see there's some conflicts.  I'll work to resolve them as soon as I can.

**Comment by jamesmortensen** [comment]
The tests in GitHub Actions now pass, and conflicts are resolved.   Please let me know if there's anything else we should change.  Otherwise, I feel this is good to go.

Since the changes were all internal to the Makefile, and since the arguments to the make build process are still the same, I don't think any changes to the README or docs are necessary.  Please let me know if that's not the case.

**Comment by jamesmortensen** [comment]
I want to add that changes to test.py were required.  test.py rebuilds containers using the Docker SDK for Python, and this required the new build arguments passed into the SDK build method.  This required the following additional changes:

- Created a FROM_IMAGE_ARGS mapping with the NAMESPACE and VERSION for the Dockerfile FROM argument.  This dictionary is passed into the Docker SDK build method as buildargs.
- Since we eliminate the Standalone[Chrome|Edge|Firefox) folders, we have a get_build_path method to use "Standalone" as the build folder for the browser images and use the original container mapping key for all others.
- Created set_from_image_base_for_standalone method to get the correct base image to use for each standalone browser image.  Additional browsers are easily added by modifying the standalone_browser_container_matches regular expression.

My goal was to make it as easy as possible to maintain.  For instance, if we ever add Opera back, or WebKit, then the regular expression would be changed from `(Standalone)(Chrome|Firefox|Edge)` to `(Standalone)(Chrome|Firefox|Edge|Opera|WebKit)`.

**Comment by diemol** [comment]
Any reason why this is now a draft? Looked good to me.

**Comment by jamesmortensen** [comment]
@diemol I wanted to validate that none of my changes affected the deploy process. I haven't done that yet, but if you think it is good to go, then we can merge.

**Comment by jamesmortensen** [comment]
Test deployment looks good.  I think we're ready to merge:  https://github.com/jamesmortensen/docker-selenium/releases/tag/4.4.0-20220817

**Review by diemol — APPROVED** [review]
Thank you, @jamesmortensen! This is great!

**Pull request merged**
