### PR TITLE
Update Dockerfile ubuntu version

### PR DESCRIPTION
**Pull request by mtcolman**
updating ubuntu version - moving to latest ubuntu:focal-xyz version

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
updating ubuntu version - moving to latest ubuntu:focal-xyz version

### Motivation and Context
Keeping base image up to date to reduce vulns

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Can you sign the CLA so I can merge this, please?

**Comment by mtcolman** [comment]
I did it just before I raised the PR?

**Comment by mtcolman** [comment]
Signed it again - hopefully done now.

**Comment by diemol** [comment]
Thank you.

**Review by diemol — APPROVED** [review]
Thank you, @mtcolman!

**Pull request merged**
