### PR TITLE
Possible temporary fix for https://github.com/SeleniumHQ/docker-selen…

### PR DESCRIPTION
**Pull request by pczerkas**
…ium/issues/1507

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

When Chrome is downgraded - no local issues with sychronization.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
How does that solve the issue?

**Comment by pczerkas** [comment]
Hi @diemol it does not solve it, it only demostrates that something may be going wrong with Chrome side. Which could be also checked by wider audience here...

**Comment by diemol** [comment]
I don't follow. So, is the issue only happening with Chrome and using an old version fixes it?

**Comment by pczerkas** [comment]
I'm using only Chrome, and that fixed some issues for me. Maybe someone is using full grid and can speak regarding issue 1507 (if errors happen only on Chrome or also on other browsers)?

**Comment by diemol** [comment]
Well, I believe we won't merge this because this would end up offering an old version of Chrome to fix an issue that is not being faced by everyone. 

However, if you have ways to help us analyze the issue through this PR, that would be very helpful. What evidence, logs, etc... can you share so we can troubleshoot better?

**Comment by pczerkas** [comment]
We could prepare some separate images with ealier version of Chrome to tests for community. I will also gather some logs from codeception and selenium.

**Comment by pczerkas** [comment]
@diemol sorry but this is false alarm. It helped for some cases of Chrome errors in Selenium 3 but for 4 it is still no go...

**Pull request closed without merging**
