### PR TITLE
Upgrading ubuntu bionic to 20200630

### PR DESCRIPTION
**Pull request by diemol**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Upgrading base image to recent ubuntu release

### Motivation and Context

Keep the base image up to date

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by edumco** [comment]
The use the shared tag `bionic` already makes the base image to be updated to the latest bionic build on Docker.

Captura de tela de 2020-07-19 17-52-11

It is a good practice to pin an exact version.

Would that create more overhead?

**Comment by diemol** [comment]
@edumco some time ago we decided to pin the base image version to control what we build things on top, and to avoid unexpected issues by using a tag that does not reference a unique image.

**Comment by edumco** [comment]
I got it, but i think you used a different version on title.

I tryed to pull and i couldnt

**Comment by diemol** [comment]
Yes, I made a typo which I had to fix in the next commit.

**Pull request merged**
