### PR TITLE
Replace x11vnc with tightvnc.

### PR DESCRIPTION
**Pull request by phensley**
I'm running my docker-selenium nodes using tightvnc to record video of browser sessions over the network. I've found it to be more responsive than x11vnc.  If there is interest in keeping x11vnc the entry point could be modularized so that either x11vnc or tightvnc could be started, e.g. `VNCSERVER=[x11vnc | tightvnc]`

### CODE REVIEW

**Comment by phensley** [comment]
Hey @mtscout6, thanks for the feedback, I'm just getting back to this now. I'll rework this a bit and push another commit.

**Comment by kayabendroth-epages** [comment]
@phensley Doesn't merge w/o conflicts any more.

**Comment by diemol** [comment]
Hi,
Is there an interest to merge this PR? If so, what is the main motivation to do so? I mean, is there some performance gaining when using TightVNC? Some numbers to support that are appreciated. 

If not, let us know and we can close the PR.

**Comment by phensley** [comment]
@diemol I no longer have interest in merging.

**Comment by diemol** [comment]
Thanks for replying @phensley, and apologies for not reacting to this earlier.

**Pull request closed without merging**
