### PR TITLE
add chinese font in base contaimer

### PR DESCRIPTION
**Pull request by b4456609**
The screenshots in selenium chrome node shows that Chinese characters display with square boxes. Install Chinese font could solve the problem.

### CODE REVIEW

**Comment by elgalu** [comment]
Note installing `fonts-noto-cjk` will add 126.7 MB to the docker image, perhaps is better generating a separate image in this case.

**Comment by HackToday** [comment]
Adding Chinese support is good. however not sure if those containers could accept such locale support for general cases. As different language may have different requrements

**Comment by ddavison** [comment]
i'm going to keep this PR open just for reference, but i've assigned a milestone that i would like to achieve with these containers, and that is internationalization.

**Comment by diemol** [comment]
Someone sent a PR to https://github.com/elgalu/docker-selenium/pull/153, with the same purpose. 
The main difference is that the installed packages only need 30MB more. Maybe this is an alternative?

**Comment by Cyperwu** [comment]
Is this Issue going any further?

**Comment by ddavison** [comment]
regarding your comment, @diemol, i tried a before-after using these packages:

- fonts-ipafont-gothic
- fonts-wqy-zenhei

Before and after had the same result - and the result looked like this:
screen shot 2018-01-22 at 1 59 24 pm

**Comment by diemol** [comment]
Closing this one since we merged #676

**Pull request closed without merging**
