### PR TITLE
chart(add): Grid scaler use trigger auth to secure GraphQL endpoint

### LINKED ISSUE #2391: [🚀 Feature]: Selenium grid Authentication password is stored as plain text in Helm chat values.yaml file
### Feature and motivation

currently the selenium grid auth password is stored as a plain text in the values.yaml of helm chart can we fetch it from secrets

### Usage example

fetch the password from  different secret stores so it is not exposed public

### PR DESCRIPTION
**Pull request by VietND96**
### **User description**

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
- Use resource TriggerAuthentication in KEDA to hide GraphQL endpoint URL and basic auth.
- Use new scaler parameter to provide `username`, `password` instead of putting in URL - https://github.com/SeleniumHQ/docker-selenium/blob/trunk/.keda/scalers/selenium-grid-scaler.md
- Fixes https://github.com/SeleniumHQ/docker-selenium/issues/2391

> Set config key `basicAuth.embeddedUrl` is `true` will be used to put basic auth credentials  in URL again

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement, tests

___

### **Description**
- Added basic authentication to various scripts and components to secure GraphQL endpoints.
- Removed basic authentication credentials from URLs and implemented them as headers.
- Enhanced error handling and logging for authentication-related issues.
- Updated Helm templates to support new authentication and autoscaling configurations.
- Added tests to verify the correct handling of authentication and URL construction.
- Updated documentation to reflect new features and security recommendations.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>12 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>check-grid.sh</strong><dd><code>Add basic authentication to grid status check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Base/check-grid.sh

<li>Added basic authentication header to curl command.<br> <li> Encoded username and password in base64 for authentication.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-0707ce4020543798772b1b4661e6a051d454145938ea228c727d1dd37e72331b">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>video.sh</strong><dd><code>Enhance video recording with GraphQL authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Video/video.sh

<li>Added handling for GraphQL endpoint authentication and errors.<br> <li> Updated video recording logic with authentication checks.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-7cd0ffe6390f76d290d88e6e4e3c360e9a797096c0b0fb76874303c5ca319f4b">+8/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>video_graphQLQuery.sh</strong><dd><code>Secure GraphQL queries with basic authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Video/video_graphQLQuery.sh

<li>Added basic authentication to GraphQL queries.<br> <li> Returned additional endpoint status and URL information.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-2d125eff3486ec8b3ba84a95d6312a76802681b97b70a558dddedb1ef0362fa7">+6/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>video_gridUrl.sh</strong><dd><code>Update grid URL handling with authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Video/video_gridUrl.sh

<li>Removed basic authentication from grid URL construction.<br> <li> Added basic authentication header to curl command.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-5c5dcc60b8fc9971dce8877b5cb1e1cea75b1eb70a259621827df4b67b1d645f">+2/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>distributorProbe.sh</strong><dd><code>Secure distributor probe with authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/distributor/distributorProbe.sh

- Added basic authentication to GraphQL endpoint checks.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-52ace535669d8ea5e550372c18c032c8c858bbefd593530146cab6a568745f99">+6/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nodeGridUrl.sh</strong><dd><code>Refactor node grid URL handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/node/nodeGridUrl.sh

<li>Removed basic authentication from grid URL.<br> <li> Added basic authentication header to curl command.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-2ceb33c26d27f14c04d3ee1463a0ed34e66f50b399413b4124387a5a5ce3b16d">+9/-13</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nodePreStop.sh</strong><dd><code>Enhance node pre-stop with authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/node/nodePreStop.sh

<li>Added basic authentication to node pre-stop signal.<br> <li> Improved logging for authentication errors.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-fbec2761651a32bd8795a681c932c174e821f4cbea9f9820f183c60350908b7d">+13/-5</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nodeProbe.sh</strong><dd><code>Secure node probe with authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/node/nodeProbe.sh

<li>Added basic authentication to node probe checks.<br> <li> Improved error handling for authentication issues.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-d857ccb50aa21728930ca9f5e0300aeb9fa49db6d34d6664fe2eb221ec50baf3">+15/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>routerGraphQLUrl.sh</strong><dd><code>Simplify router GraphQL URL handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/router/routerGraphQLUrl.sh

- Removed basic authentication from router GraphQL URL.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-5c905604400742d83bf3627f5d28f6fcafce950e2da12b9af034e7643ccbbc02">+1/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>routerProbe.sh</strong><dd><code>Secure router probe with authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/configs/router/routerProbe.sh

- Added basic authentication to router probe checks.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-79e2439957a5bf5ced3cdadc03431ef22890fd0f75d3679e0b4bcc4cb8cf32cb">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>_helpers.tpl</strong><dd><code>Enhance templates with authentication support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/_helpers.tpl

<li>Added template for basic authentication secrets.<br> <li> Updated autoscaling authentication reference handling.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-a57e8d3d1ad8ed854bf7e00ac004560f3dfe6d1178d5c5d45e455f8eaeb53361">+14/-4</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>basic-auth-secret.yaml</strong><dd><code>Add basic authentication secret template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/templates/basic-auth-secret.yaml

- Added new template for basic authentication secret.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-783b8f0f84b43aa7b68e106ddaee5c8f691214098adbd5349d81d76cfd993821">+21/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>test.py</strong><dd><code>Add tests for basic authentication and URL handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/charts/templates/test.py

<li>Added tests for basic authentication handling.<br> <li> Verified GraphQL URL construction without basic auth in URL.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-313e81a96e34d08dcd821e7a1223f59ffce689433658ae3999a26fc7f6dcb343">+44/-16</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>CONFIGURATION.md</strong><dd><code>Update configuration documentation for new features</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/CONFIGURATION.md

- Documented new basic authentication and autoscaling options.

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-8f21b9acf6691fc99d88780146e016715fe83ed0b5ef37fe81455f892d347786">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README with new scaler and security info</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

charts/selenium-grid/README.md

<li>Added section for new Selenium Grid Scaler implementation.<br> <li> Updated security recommendations for Grid URL.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2401/files#diff-fc10bcbda83e36362ecb788d804050f34349dd654dfedca83d53ad34b0f19e08">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by VietND96** [comment]
@Doofus100500, if removing basic auth putting in URL when constructing env var `SE_NODE_GRID_URL`. Do you think it might cause any issue for Playwright tests rely on CDP Websocket URL in node capabilities?

**Comment by VietND96** [comment]
To balance any requirement, config key `basicAuth.embeddedUrl` will be used to embed basic auth credentials to `SE_NODE_GRID_URL` if needed

**Comment by Doofus100500** [comment]
@VietND96 Removed basic auth from the URL in the SE_NODE_GRID_URL variable in the cluster with basic authentication, the Playwright test passed successfully

**Comment by VietND96** [comment]
Thank you for your confirmation. I think we are good to go with this change

**Comment by farioas** [comment]
Looks like it's breaking change in helm 0.36.0.

After upgrade, nodes are not scaled, while in KEDA we have this exception:
```
2024-09-23T10:46:26Z	ERROR	scale_handler	Error getting scaler metrics and activity, but continue	{"scaledJob.Name": "selenium-grid-selenium-firefox-node", "Scaler": "*scalers.seleniumGridScaler:", "error": "error requesting selenium grid endpoint: selenium grid returned 401"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledJobMetrics
	/workspace/pkg/scaling/scale_handler.go:853
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).isScaledJobActive
	/workspace/pkg/scaling/scale_handler.go:897
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:262
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:182
```

This is happened because existing implementation of selenium grid scaler in KEDA 2.15.1 expects to receive:
```
graphql-url: base64 encoded value of GraphQL URL
```


Fyi, this change wasn't merged https://github.com/kedacore/keda/pull/6169

**Comment by VietND96** [comment]
@farioas, if there is no dependency, can you replace registry and tag to use KEDA components in our build https://github.com/SeleniumHQ/docker-selenium/blob/trunk/.keda/README.md

**Comment by VietND96** [comment]
@farioas, can you also try to enable `basicAuth.embeddedUrl` is true, basic auth will be embedded in GraphQL endpoint as the old format.

**Comment by VietND96** [comment]
Ok, looks like `basicAuth.embeddedUrl` not worked for GraphQL endpoint. I will give a fix in `0.36.1` soon

**Comment by farioas** [comment]
It was 6hrs ago, so I tried to play with embeddedUrl, but it didn't work. So I rolled back to 0.35.2 and pinned image to `4.25.0-20240922`.

**Pull request merged**
