### PR TITLE
Feature multiarch

### PR DESCRIPTION
**Pull request by rbonghi**
Hi all,

Following the idea from https://github.com/DeinChristian/rpi-docker-selenium I add in this repo the Chromium browser, usually available in embedded world and I fixed the Base\Dockerfile to be compilable for ARMV7 (arch 32) and ARMV8 (arch 64) 
In detail I changed this line: https://github.com/rbonghi/docker-selenium/blob/feature_multiarch/Base/Dockerfile#L29 for an automatic find the right architecture folder.

Recap:
- [X] fix multi architecture (Tested for x86 and ARM64, I think can work for ARM32)
- [X] Added Chromium

I hope this update is useful for the community.

Best,
Raffaello

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by diemol** [comment]
Hi @rbonghi,

Thanks for the effort! I would like to understand what is the benefit of having Chromium vs. already having Chrome? What would this add to the project? 
Just wondering since people can already use Chrome, and I don't know how many people actually use Chromium as their daily browser, which would make the case for testing.

**Comment by rbonghi** [comment]
Hi @diemol ,

The Chrome browser at this time is not available for ARM architecture, eg. [Raspberry PI](https://www.raspberrypi.org/), [BeagleBone Black](https://beagleboard.org/black) and in my case the [NVIDIA Jetson Xavier](https://developer.nvidia.com/embedded/buy/jetson-agx-xavier-devkit) and [TX2](url). The only way to use selenium in ARM context is to work with Chromium, otherwise I am agree with your opinion.

I do not understand why travis CI make my pull request in fail. I launch on my PC the same script but I didn't see any type of errors.
```
USE_RANDOM_USER_ID=true VERSION="$TRAVIS_BRANCH" make ci
```

PS: I see that chrome will be release this year for ARM 🤞 
https://www.theverge.com/2018/11/21/18106162/microsoft-google-chrome-windows-10-arm-support-app

**Comment by diemol** [comment]
Ok, I get it.
Maybe you can keep the project in your repo and we add a link in the README here in case someone wants to use Chromium for the reasons you give, so we can let people know that there is something they can use until Chrome is released for ARM.
What do you think?

**Comment by rbonghi** [comment]
My idea was to make this repo official in short time and pull directly from the source the right version of selenium. 😄 
Anyway, we can wait the google chrome browser for ARM. I hope will be release soon.
If you are agree I will push on docker hub the ARM32 and ARM64 with chromium.

We can keep some features from this branch and start a new pull request to move this repo to be [official](https://docs.docker.com/docker-hub/official_images/), eg: fix java and ubuntu version for generic architecture.

**Comment by diemol** [comment]
>My idea was to make this repo official in short time and pull directly from the source the right version of selenium

What do you exactly mean? To add Chromium images to the already existing Firefox and Chrome images? If so, I don't think it makes sense because the idea of this images is to provide a broad, common use case tools for users. Chromium is not broadly used for testing so it would not really belong here. 
Additionally, adding a browser that potentially will be removed when Chrome is released with ARM support, just increases maintenance and would confuse users. 

>If you are agree I will push on docker hub the ARM32 and ARM64 with chromium.

Where would you push it?

>We can keep some features from this branch and start a new pull request to move this repo to be [official](https://docs.docker.com/docker-hub/official_images/), eg: fix java and ubuntu version for generic architecture.

Sure, do you know what needs to be done?

**Comment by rbonghi** [comment]
> What do you exactly mean? To add Chromium images to the already existing Firefox and Chrome images? If so, I don't think it makes sense because the idea of this images is to provide a broad, common use case tools for users. Chromium is not broadly used for testing so it would not really belong here.
> Additionally, adding a browser that potentially will be removed when Chrome is released with ARM support, just increases maintenance and would confuse users.

My initial idea was to add Chromium, but now I am agree with you to wait the new release of Chrome for ARM, make confusion for other users in this official repository.

About the multi architecture, the official docker hub documentation is only clear for official images: [multiple-architectures](https://github.com/docker-library/official-images#multiple-architectures) . The docker library build the images for each architecture when is written the [library definition file](https://github.com/docker-library/official-images#library-definition-files) otherwise the Automated tool build only in "amd64" version.

Make this library official help me to pull from docker hub the right version of selenium without build on embedded board (and safe time) the image.

> Where would you push it?

In my personal account [rbonghi](https://hub.docker.com/u/rbonghi/). Only the version for arm32 and arm64

> Sure, do you know what needs to be done?

The steps to follow are explained here: [Contributing to the standard library](https://github.com/docker-library/official-images#contributing-to-the-standard-library)
I think does not require to make this repository official, just clean some parts and add security check in some downloads, like https://github.com/docker-library/official-images#security

I think this repo have the number to be official [NEW-IMAGE-CHECKLIST.md](https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md)

**Comment by diemol** [comment]
OK, so there are a few things here:

- Yes, so if I understood, it would be great if you host the repo on your user and push the images to your user space in Docker Hub, we would happiliy add a link to it in the README that belongs to this project.

- Having this set of images as offical, there was an effort to do that earlier https://github.com/SeleniumHQ/docker-selenium/milestone/1?closed=1, but I don't know how that ended. Additionally, I am not sure what added value it would bring.

So in terms of this PR, I think there is nothing to do here. @rbonghi if you want to, send us a PR with the link to your GitHub repo where the code for the Chromium images is.

Besides that, I think we can close this PR. What do you think?

**Comment by rbonghi** [comment]
Hi @diemol ,

> * Yes, so if I understood, it would be great if you host the repo on your user and push the images to your user space in Docker Hub, we would happiliy add a link to it in the README that belongs to this project.

Ok, I hope for this week I will update my repo to show only selenium with Chromium for arch ARM32 ARM64

> * Having this set of images as offical, there was an effort to do that earlier https://github.com/SeleniumHQ/docker-selenium/milestone/1?closed=1, but I don't know how that ended. Additionally, I am not sure what added value it would bring.

Ops, I did not see that milestone. Maybe I can send you a new pull request only with the fix for ARM, in detail only this change [Base/Dockerfile](https://github.com/SeleniumHQ/docker-selenium/pull/876/files#diff-b3a44b8ada80650b62db3d7c9ddabcc1) and finally I open a new issue with some fix to move this dockers to be official.

Yes, we can close this pull request :+1:

**Pull request closed without merging**
