### PR TITLE
#91 Xvfb failed to start fix

### PR DESCRIPTION
**Pull request by gurukiran007**
The fix is to make sure that the password used by VNC is created by "seluser" and not as root due to which the entrypoint script fails. Only
impacts all debug node containers
This must fix issues i guess:
#91
#205
#76
#257
#253

### CODE REVIEW

**Comment by marcinbojanowski** [comment]
Works for me! :D

**Comment by alexgandy** [comment]
Worked for me as well

**Comment by ahmadrabie** [comment]
I need this too.
@kayabendroth please merge it ASAP.
Thanks :)

**Comment by saikrishna321** [comment]
@kayabendroth can this be merged

**Comment by zouxuoz** [comment]
@kayabendroth merge this please

**Comment by pproenca** [comment]
@kayabendroth is it possible to merge this PR?

**Comment by schmunk42** [comment]
Ping...

**Comment by ddavison** [comment]
could you please rebase your branch?  then i'll merge it in

**Comment by zouxuoz** [comment]
//summon @gurukiran007

**Comment by gurukiran007** [comment]
Done can you guys see if this helps now...

**Comment by vikramvi** [comment]
@gurukiran007  I tried docker run -P -p 5901:5901 -e no_proxy=localhost -e HUB_ENV_no_proxy=localhost --link selenium-hub:hub selenium/node-chrome-debug:2.53.1 and got error

Unable to find image 'selenium/node-chrome-debug:2.53.1' locally
Pulling repository docker.io/selenium/node-chrome-debug
docker: Tag 2.53.1 not found in repository docker.io/selenium/node-chrome-debug.
See 'docker run --help'.

**Comment by gurukiran007** [comment]
Master has removed the docker file :
https://github.com/SeleniumHQ/docker-selenium/tree/master/NodeChromeDebug

**Comment by gurukiran007** [comment]
@vikramvi does that work on master for you ?

**Comment by vikramvi** [comment]
@gurukiran007 can you please give command which I can try , struggling with debug version since almost 1/2 day now :( thanks in advance.

**Comment by gurukiran007** [comment]
@vikramvi :
STEP 1: build the version you want, after you have cloned the repo, run this: VERSION=2.53.1 make build
STEP 2: build the images you want from the docker files generated from step 1
STEP 3: Run the command you shared

@ddavison can you please merge this to master. I have rebased the branch from master.

**Comment by gurukiran007** [comment]
@kayabendroth can you help please  i cannot understand why the build fails after i have rebased from master

**Comment by schmunk42** [comment]
@gurukiran007 From the logs it looks to me like `test.sh` is not building `selenium/test:local` for some reason.

I'd also expect to see the echo output from https://github.com/gurukiran007/docker-selenium/blob/89a6026d5191bab02c1e254bff44c251724c373e/test.sh#L22 in the logs?!

**Comment by ddavison** [comment]
yea - i've been fiddling around with it trying to get it to work to no avail.. i'm very tempted to wipe it out and try something with travis

**Comment by ddavison** [comment]
good news! i've got [travis integration working](https://travis-ci.org/ddavison/docker-selenium/builds/163817330).  i'll be working on implementing this

**Comment by ddavison** [comment]
do me a favor @gurukiran007 and push another commit.. your build should pass when run through travis.  (gotta invoke it first with a commit)

**Comment by ddavison** [comment]
one more test, then this puppy is going in

**Comment by gurukiran007** [comment]
Sounds good thanks @ddavison

**Comment by ddavison** [comment]
@gurukiran007 , are you able to successfully run your NodeChromeDebug container?  i see that it's done waiting for xvfb, but fails on Xserver stuff, ultimately killing the container

**Comment by ddavison** [comment]
```
dj@Daniels-MBP:~/workspace/docker-selenium|0472fd3
⇒  docker run 02a38ad73b5b
/opt/bin/entry_point.sh: line 5: /opt/bin/clear_x_locks.sh: No such file or directory
Waiting xvfb...
-bash: 169.254/16: No such file or directory
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
dj@Daniels-MBP:~/workspace/docker-selenium|0472fd3
⇒
```

**Comment by gurukiran007** [comment]
Let me re test it locally ... that does not look right ...

**Comment by ddavison** [comment]
were you able to find out the issue?  the chrome-debug image is still unstable for some reason.. i haven't been able to narrow it down just yet

**Comment by ddavison** [comment]
i found the issue - it's due to [this issue in docker](https://forums.docker.com/t/space-in-new-no-proxy-env-var-breaking-old-containers/14075) that i was unable to build successfully.

**Comment by gurukiran007** [comment]
Thanks @ddavison for closing that and sharing the docker bug.. the explains the local issue i had as well.. 👍

**Comment by ddavison** [comment]
sorry i couldn't give your commit credit there.. i did pull pieces of yours in to use, but i'm trying to organize everything in the repository.. merging it in from github would've been uncomfortable as it is right now.. it'll be stable shortly, where i can accept PR's from github :P

**Comment by ddavison** [comment]
wait, @gurukiran007 - what were we thinking.. the entry_point.sh is called by root, NOT seluser.  the xvfb-run command is executed by seluser, not root.  

a lot of people said this works for them, but it makes no sense why it does.  i just took a a look at https://github.com/SeleniumHQ/docker-selenium/issues/291 and this happens when .vnc/ is in /home/seluser, but passes when in /root/.vnc.

**Comment by gurukiran007** [comment]
@ddavison I see what you mean, 
The fix was done before the new call/last call in the script with x11vnc is being made in entry_point.sh presently, 

The defect it fixed was that the docker file created the password  with root: http://screencast.com/t/DIIpZvARg
And tried to access it using seluser http://screencast.com/t/sj0QLXfspi 
But as you mentioned now that we have one more call to start the x11vnc would be happy if i do that as seluser as well?

**Comment by ddavison** [comment]
well, i have #292 working right now, so i think i'll merge that in.  I don't believe it matters who is running x11vnc

**Comment by gurukiran007** [comment]
Ok, but i believe that fix will again not allow the VNC server to be up as `xvfb-run -n $SERVERNUM --server-args="-screen 0 $GEOMETRY -ac +extension RANDR" ` tries to look for password in seluser home directory but the password is saved in root home and hence will fail

**Comment by ddavison** [comment]
i believe your assumption is incorrect.  xvfb-run runs as seluser, sure, but x11vnc running as root really doesn't matter vs running as seluser. 

chrome-debug-vnc

**Pull request closed without merging**
