### PR TITLE
Change right for /opt/bi/*.sh file. Impact of change on Base/Dockerfi…

### PR DESCRIPTION
**Pull request by eravion**
…le file (replace 777 by 775)

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Can you explain better why this is needed?

**Comment by eravion** [comment]
Hello @diemol ,
Change needed because of  https://github.com/SeleniumHQ/docker-selenium/pull/1963
Our security Dept. does not allow 777 rights on folder. Including on docker.

**Review by diemol — CHANGES_REQUESTED** [review]
Please do the `COPY` with `chmod` as mentioned in the Docker documentation https://docs.docker.com/engine/reference/builder/#copy

**Comment by VietND96** [comment]
> Hello @diemol ,
> 
> Change needed because of  https://github.com/SeleniumHQ/docker-selenium/pull/1963
> 
> Our security Dept. does not allow 777 rights on folder. Including on docker.

Hi @eravion, can you please combine this commit into #1963 to see all changes needed, test it and merge those together?

**Comment by VietND96** [comment]
This one is also considered via PR #2056. You can review it once.

**Comment by VietND96** [comment]
Close this PR as per comments in #1963

**Pull request closed without merging**
