### PR TITLE
Add Node HtmlUnit

### PR DESCRIPTION
**Pull request by eedgar**

### CODE REVIEW

**Comment by mtscout6** [comment]
Can you add some kind of test that exercises this new image?

**Comment by eedgar** [comment]
mtscout6 I can try but I am not sure what the testing framework here is doing yet.  I just started looking at this project the other day.

**Comment by eedgar** [comment]
Mtscout6,  I took a look at the tests in this package and it appears they are already broken.  Eg it looks like the firefox tests are always skipped and Adding my htmlunit test wont run either because the last node command in the Docker file is what is run.

**Comment by eedgar** [comment]
mtscout6, I figured out the issue Docker wasn't passing && correctly in the env variables.  I have created a test for this feature now.

**Comment by rubytester** [comment]
tests fixed in pull request #67 

please rebase to master

see tests are isolated now, they only call one browser at a time. initial TEST_CMD is a <blank> string, tests add a smoke test command.

**Comment by kowalcj0** [comment]
Hi Guys, 

Any updates on this ticket?

Cheers

**Comment by ddavison** [comment]
this seems functionally invalid.. at the very least, i'd expect your dockerfile to download the [htmlunitdriver](https://github.com/SeleniumHQ/htmlunit-driver), but it doesn't.

**Comment by diemol** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
