### PR TITLE
corrected typo in selenium grid charts

### PR DESCRIPTION
**Pull request by Thab310**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Spelling error correction

### Motivation and Context
This change will make the comment make sense and will help avoid ambiguity. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
@amardeep2006 do you know why is the linting now failing?

**Comment by diemol** [comment]
@amardeep2006 
>✖︎ selenium-grid => (version: "0.25.0", path: "charts/selenium-grid") > chart version not ok. Needs a version bump! 

Why? We do not need to bump the version for this change.

**Comment by amardeep2006** [comment]
@diemol Yes seems ct has linting rule which expects version to be bumped up as well.
Let me know if we need to disable this check.  There is a flag called `--check-version-increment` which can be used to control this behavior.  `--check-version-increment` 

Please let me know if this is required or we are ok with version bump from contributors.

**Review by diemol — APPROVED** [review]
Thank you, @Thab310!

**Pull request merged**
