### PR TITLE
Always download latest stable Firefox by default

### PR DESCRIPTION
**Pull request by testphreak**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by testphreak** [comment]
Adding a minor change, so whenever a new image is created with a new version of Selenium, whatever the latest stable Firefox is at that time, gets downloaded by default as part of the build, just as we do today with Chrome. Hopefully if this change is accepted, we will not need new pull requests for new versions of stable Firefox.

**Comment by testphreak** [comment]
@diemol, @ddavison can we get this merged?

**Comment by diemol** [comment]
Hi @testphreak,

Thanks for the PR! We'll do a review during the weekend to merge and then release with the new FF version 59.0.2

**Comment by testphreak** [comment]
Thanks @diemol. I made a minor change to not add an else if condition to an already long line. The downside to that is folks who were previously specifying just `devedition` or `nightly`, now need to add `devedition-latest` or `nightly-latest`.

**Comment by diemol** [comment]
Just tested it and it works! Thanks @testphreak

**Comment by ddavison** [comment]
we already do this for Chrome, so makes sense we have this for FF.  👍

**Pull request merged**
