### PR TITLE
WIP: add ability to install specific chrome version. fixes #266

### LINKED ISSUE #266: Feature request:node-chrome docker image :Request team to make the dockerfile generic to add a version parameter like node-firefox image, so that we can build different versions of chrome nodes.
Request team to make the dockerfile generic to add a version parameter like node-firefox image, so that we can build different versions of chrome nodes.

### PR DESCRIPTION
**Pull request by ddavison**
hold off merging until I test this thoroughly.  I will merge it in once i'm done.

### CODE REVIEW

**Comment by davehunt** [comment]
@ddavison if your comfortable doing merges on this repo, then would you mind taking a look at #251 which does something similar for the Selenium server component and Firefox?

**Comment by ddavison** [comment]
sure thing, @davehunt

**Comment by finspin** [comment]
Is this waiting for tests or? We would need this feature because we need to use some older versions of Chrome.

**Comment by elgalu** [comment]
I don't how this can work for installing old versions of chrome, right now we are on Chrome 56 (stable) and if I try to install Chrome 53 the package is not listed anymore:

```sh
E: Version '53.0.2785.101-1' for 'google-chrome-stable' was not found
```

What am I missing?

**Comment by ddavison** [comment]
@elgalu:

```sh
BUILD_ARGS="--build-arg CHROME_DRIVER_VERSION=2.23 --build-arg CHROME_VERSION=google-chrome-beta=53.0.2785.92-1" make chrome chrome_debug standalone_chrome
```

**Pull request merged**
