### PR TITLE
Add instructions for connecting Grid Node to Hub on another machine

### PR DESCRIPTION
**Pull request by alexkogon**

### CODE REVIEW

**Comment by rubytester** [comment]
Forgot to ask to: Please rebase and git commit append so it's just one commit to merge. 

Please kindly sign the the CLA as described here

https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md

**Comment by rubytester** [comment]
This is related to the case 2 in Issue #133 

To clarify: `HUB_PORT_4444_TCP_ADDR` has to be a hostname or an IP address - example:  `hub.example.com` or `192.168.1.22` or some values.

**Comment by defender** [comment]
The problem still exists we don't want to work with hardcoded node port.

**Comment by alexkogon** [comment]
@defender not sure what you mean, this seems to work.

@rubytester I added what you asked for

**Comment by tparikka** [comment]
At this time, using -e REMOTE_HOST=http://<ThisDockerHostsAdress>:5555 as recommended in the revised readme causes the following error to be thrown in Docker-Win Version 17.03.1-ce-win5 (10743) (when using docker-compose and a v2 yml file, anyways):

REMOTE_HOST variable is *DEPRECATED* in these docker containers.  Please use SE_OPTS="-host <host> -port <port>" instead!

**Comment by ddavison** [comment]
I'll work on creating a wiki page entry for this, instead of the README.md.  i'll link it from the readme as well.

**Pull request closed without merging**
