### PR TITLE
update to latest chromedriver 2.32

### PR DESCRIPTION
**Pull request by seamusabshere**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by glib-briia** [comment]
No longer required since #545

**Comment by seamusabshere** [comment]
@glib-briia OK, what will kick off a new docker build? somebody else needs to merge something to master?

**Comment by glib-briia** [comment]
That will be available with the next release

**Comment by jsa34** [comment]
@glib-briia When is the next release due?

**Comment by diemol** [comment]
Hi, I'll check this PR between today's evening and tomorrow. 
I'll make a new release including it, I was getting details on the release process. 
Basically after the release, I'll close this PR since #545 already implemented it.

**Comment by jsa34** [comment]
Fab!  Thanks for the info, diemol!

**Pull request closed without merging**
