### PR TITLE
feat(helm-test): Added helm test and linting

### LINKED ISSUE #1975: Helm Charts maintainer needed
### Feature and motivation

We have been unable to handle updates and proper testing for the helm chart. We are looking for someone who wants to maintain them long-term.

### Usage example

If we do not find someone by the end of November 2023, we will move the chart to the https://github.com/seleniumhq-community organization.

### PR DESCRIPTION
**Pull request by amardeep2006**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
This is related to https://github.com/SeleniumHQ/docker-selenium/issues/1975

1. Added a workflow to lint and test helm charts
2. Added maintainer info in Charts.yml
3. Did one time linting for issues thrown by linter

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Seems the new action is failing.

**Comment by VietND96** [comment]
In part of this PR, could you please update appVersion of Chart to be aligned with today image tag 4.15.0-20231110?

**Comment by VietND96** [comment]
Warning  FailedScheduling  5m    default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

Looks like the cluster doesn't have enough resource to start the default setup

**Comment by amardeep2006** [comment]
@diemol Please rerun the failed job, most probably GitHub runner ran out of computes while running k8s. Seems like intermittent issue. Happened with me as well once it worked on retry.
See the successful run on my forked repo : https://github.com/amardeep2006/docker-selenium/actions

**Comment by amardeep2006** [comment]
> In part of this PR, could you please update appVersion of Chart to be aligned with today image tag 4.15.0-20231110?

I just did and pushed the commit.

**Comment by VietND96** [comment]
I saw the condition to trigger the workflow is on pull request.
Do we need to consider the combination of PR and contain changes in path charts/selenium-grid?

**Comment by amardeep2006** [comment]
> I saw the condition to trigger the workflow is on pull request. Do we need to consider the combination of PR and contain changes in path charts/selenium-grid?

This is handled in workflow. It first checks if there are some changes in helm chart and only then then executes the remaining steps.

image

**Comment by VietND96** [comment]
Cool, how about if we handle on the trigger events, something like
```yaml
on:
  pull_request:
    paths:
      - 'charts/selenium-grid/**'
```
I am referring to
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/.github/workflows/helm-chart-release.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request

**Comment by amardeep2006** [comment]
> Cool, how about if we handle on the trigger events, something like
> 
> ```yaml
> on:
>   pull_request:
>     paths:
>       - 'charts/selenium-grid/**'
> ```
> 
> I am referring to https://github.com/SeleniumHQ/docker-selenium/blob/trunk/.github/workflows/helm-chart-release.yml https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request

May be a separate PR as continuous improvement. It will take time to test new logic. The current if conditions are tested by me already.

**Comment by diemol** [comment]
> > Cool, how about if we handle on the trigger events, something like
> > ```yaml
> > on:
> >   pull_request:
> >     paths:
> >       - 'charts/selenium-grid/**'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am referring to https://github.com/SeleniumHQ/docker-selenium/blob/trunk/.github/workflows/helm-chart-release.yml https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request
> 
> May be a separate PR as continuous improvement. It will take time to test new logic. The current if conditions are tested by me already.

I would prefer to have this already. Thanks!

**Comment by VietND96** [comment]
While fixing another breakage, I have used your baseline to update trigger events, pull out configs for `ct` to a separate file, and add a test with multiple desired values files. PR #2009
The PR doesn't pick Lint update, so it failed. I commented out that step. I think will bring it back in your PR after merging.

**Review by diemol — APPROVED** [review]
Thank you, @amardeep2006!

**Pull request merged**
