### PR TITLE
Refine lang setting

### LINKED ISSUE #1750: [🐛 Bug]: Setting lang attribute doesn't apply to the test containers
### What happened?

When trying to run with a different locale, trying all possible ways to set this via the chromedriver doesn't seem to work.

Apparently there is an issue with setting this, and needs to be done at the env variable level.  This was previously identified:
https://github.com/elgalu/docker-selenium/issues/159

And I am still seeing the same behaviour in the current docker selenium images.

### Command used to start Selenium Grid with Docker

```shell
Using dynamic grid as documented on README.md
```

### Relevant log output

```shell
N/A

However, no matter what I set, the browser always is set to en_US and en as the languages in the settings section of the browser when inspecting.
```

### Operating System

Centos 9

### Docker Selenium version (tag)

4.5.0

### PR DESCRIPTION
**Pull request by jsa34**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Sets the LANGUAGE env var as part of the binary wrapper script, instead of outside it,

### Motivation and Context

Resolves #1750.
Previous attempt didn't permeate to the node container in dynamic grid setup.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsa34** [comment]
@diemol  - could you give this a look when you have time to make sure I am taking the right approach to make sure the env variable is set in the dynamic node containers?

**Review by diemol — COMMENTED** [review]
This is quite tricky to test. The script looks fine to me.

Have you built the images locally to test it? If you tell me that it works, I'd be happy to merge it and release.

**Review by diemol — APPROVED** [review]
Thank you, @jsa34!

**Comment by diemol** [comment]
> This is quite tricky to test. The script looks fine to me.
> 
> Have you built the images locally to test it? If you tell me that it works, I'd be happy to merge it and release.

The PR looks good. However, I am still waiting for your reply on this question, @jsa34.

**Comment by jsa34** [comment]
Apologies  - I haven't had a chance yet, but will try to today
________________________________

**Comment by diemol** [comment]
👍 
Please let me know and I'd be happy to do a release after that.

**Comment by jsa34** [comment]
Built images locally (hopefully correctly as I have to use a Windows machine with WSL2) and looks ok.

I could only check the standalone locally, but logically should be fine with dynamic grid.
________________________________

**Pull request merged**
