### PR TITLE
Install Python2, Python2 PIP and Selenium for Python in the base image

### PR DESCRIPTION
**Pull request by alistair23**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by diemol** [comment]
Hi @alistair23,

Thanks for sending us a PR. Could you please tell us what is the need to install Python in the images?

**Comment by alistair23** [comment]
I use Selenium in Docker containers by running Python scripts. I thought it might be beneficial to install python with selenium support in the base image.

**Comment by diemol** [comment]
Well, yes, it would benefit users who have tests in python. But this would leave out users who use ruby, java, etc...

Bottomline, the images try to be a generic as possible, and this would go against that concept. That's why I think we cannot accept this PR, sorry.

**Comment by alistair23** [comment]
That's fair. Is there any plan on having larger more complete images or maybe specific development images in the future?

**Comment by diemol** [comment]
Not really, at least not officially. You could use this one https://github.com/elgalu/docker-selenium, which already has Python installed (but it is a heavier image).

I'll close the PR :)

**Comment by alistair23** [comment]
No worries.
Is the first patch (just the upgrade) ok to be merged?

**Comment by diemol** [comment]
Hm, maybe, I am not sure about the benefit. But you could send the PR and then we discuss it also with @ddavison

**Pull request closed without merging**
