### PR TITLE
Update chromedriver to 2.23

### PR DESCRIPTION
**Pull request by smccarthy**
Chromedriver 2.22 is out which supports Chrome 49 - 52.

https://chromedriver.storage.googleapis.com/2.22/notes.txt

### CODE REVIEW

**Comment by testphreak** [comment]
@smccarthy would be great to see this update merged. Contains several fixes.

**Comment by Davidrums** [comment]
@kayabendroth

**Comment by MartinNuc** [comment]
There is 2.23 already :-) https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by smccarthy** [comment]
@MartinNuc Thanks. Updated to 2.23.

**Comment by ddavison** [comment]
this also is related to #250.  we may need to close this one as another duplicate.

**Comment by ddavison** [comment]
this was fixed in c338b611e5df5a314ad18d32fab38b5aaa4d4a79

**Pull request closed without merging**
