### PR TITLE
New tests

### PR DESCRIPTION
**Pull request by diemol**
New test suite #476
@ddavison, can you please help me to review it? My python is a bit rusty...
 
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by diemol** [comment]
Found some python issues when trying to run the tests in Travis.

**Comment by ddavison** [comment]
looks good so far!

**Comment by diemol** [comment]
Now the build looks good! :)

**Comment by diemol** [comment]
Closes #476

**Pull request merged**
