### PR TITLE
Fix work with environment variables at `xvfb-run` (2nd time)

### LINKED ISSUE #423: Passing SE_OPTS in docker-compose
I'm having problems setting SE_OPTS variable via docker-compose version 3.0 file. Here is my setup:

Docker version: Docker version 17.03.0-ce, build 60ccb22
docker-compose version: docker-compose version 1.11.2, build dfed245

```
# hub-docke-compose.yml
version: '3.0'
services:
  hub:
    image: selenium/hub:3.2.0
    container_name: hub-standalone
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=10
      - GRID_TIMEOUT=90
      - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
      - GRID_THROW_ON_CAPABILITY_NOT_PRESENT=false
    ports:
      - 4444:4444
```

```
# node-chrome-standalone.yml
version: '3.0'
services:
  chrome:
    image: selenium/node-chrome-debug:3.2.0
    container_name: node-chrome-remote
    ports:
      - 5555:5555
      - 5900:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=XX.XX.XX.XX
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
      - SE_OPTS="-host YY.YY.YY.YY -port 5555"
      # Some other things I tried
      # - SE_OPTS=-host YY.YY.YY.YY -port 5555
      # command: bash -c 'SE_OPTS="-host YY.YY.YY.YY -port 5555" /opt/bin/entry_point.sh'
      # command: bash -c 'export SE_OPTS="-host YY.YY.YY.YY"'
    shm_size: 2G
``` 

It seems like it doesn't understand the SE_OPTS variable. It interprets YY.YY.YY.YY (which is the actual node host IP) as a command?

```
Attaching to node-chrome-remote
node-chrome-remote | appending selenium options: "-host YY.YY.YY.YY -port 5555"
node-chrome-remote | Waiting xvfb...
node-chrome-remote | -bash: YY.YY.YY.YY: command not found
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote | Waiting xvfb...
node-chrome-remote exited with code 127
```

### PR DESCRIPTION
**Pull request by diemol**
This is just making the same change @METAJIJI did in #445 which fixes #423, but got overwritten in #455, therefore the current release 3.3.1-cesium brought that bug back. I'm just adding the same change for the Firefox Debug image and the Standalone images.

Tested it locally by building the images and using the docker-compose file provided in #423, the change done by @METAJIJI works.

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by elgalu** [comment]
:+1:

**Comment by diemol** [comment]
@ddavison, maybe we can enable this setting in the repo to avoid having these type of issues with PRs? (Getting stuff overwritten).

image

**Comment by ddavison** [comment]
done :)

**Comment by vimagick** [comment]
:+1:

**Pull request merged**
