### PR TITLE
91 xvfb failed to start

### PR DESCRIPTION
**Pull request by garagepoort**

### CODE REVIEW

**Comment by caioquirino** [comment]
@kayabendroth I'm tested and works. Thanks @garagepoort

**Comment by garagepoort** [comment]
Hi @kayabendroth 
Happy to help, but the tests failed. Could you shed some light on that?

**Comment by garagepoort** [comment]
@mtscout6 Is this project still maintained? No comments were given on my pull request

**Comment by mtscout6** [comment]
My understanding was that @rubytester had taken over. I made a request to the @SeleniumHQ/selenium-committers dev mailing list to add @kayabendroth as another maintainer, but I don't think that actually happened. I'll do some follow up this week to figure out who is maintaining this now. I had to step away due to other work obligations, though I still see immense value in this project and do hope to see it's success. My goal for any OSS project I work on is to have multiple maintainers from multiple companies so as to avoid bottlenecks. I apologize for the delay.

**Comment by lukeis** [comment]
They were added-
https://github.com/orgs/SeleniumHQ/teams/docker-owners

**Comment by lukeis** [comment]
Open source, volunteer, yadda yadda... No need to apologize @mtscout6 :)

**Comment by garagepoort** [comment]
@mtscout6 Indeed no need to apologize :) I just pulled you because you were the top volunteer on this project. I am glad it is still maintained as it is of great value for the company I work at.

**Comment by caioquirino** [comment]
@lukeis and @mtscout6 
I would like to spend some time testing, validating PR and contribute with the project. What's the correct path to contribute with the project?

**Comment by garagepoort** [comment]
@caioquirino although I am glad my PR is getting so much attention, I think we wandered off from the essence of the PR. Might be good to start private conversation ;-)

**Comment by kayabendroth** [comment]
Was busy during the last weeks.

**Comment by benfortuna** [comment]
Will this fix be applied to the other images also (firefox/firefox-debug/chrome)? I can confirm the issue exists in the standalone-chrome image.

**Pull request merged**
