### PR TITLE
reject-unsupported-caps to true

### LINKED ISSUE #14339: [🐛 Bug]: Fly.io
### What happened?

I started a selenium stand alone (selenium) server in fly.io using the docker container. However, when I send requests to the url the test are stuck in the queue and are not run.

Screenshot 2024-08-03 153613
Screenshot 2024-08-03 153635

### How can we reproduce the issue?

```shell
Create a folder with a dockerfile in it with the following contents: 

FROM selenium/standalone-edge:latest
WORKDIR /app

Then run fly launch, which will launch the docker container to fly.io.

Then make a connect to the server remotely programmatically. I do did so via the following code: 

$serverUrl = env('SELENIUM_URL', false);
$driver = RemoteWebDriver::create($serverUrl, DesiredCapabilities::chrome());
$driver->get('[any website of choice]');
$text = $driver->findElement(WebDriverBy::tagName('tbody'))->getText();
```

### Relevant log output

```shell
n/a
```

### Operating System

Windows 11

### Selenium version

selenium/standalone-chrome (image)

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome

### Are you using Selenium Grid?

4.23.0

### PR DESCRIPTION
**Pull request by diemol**
### **User description**

Fixes https://github.com/SeleniumHQ/selenium/issues/14339

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Added `--reject-unsupported-caps` parameter to the Java command execution in `start-selenium-standalone.sh`.
- Introduced `SE_REJECT_UNSUPPORTED_CAPS` environment variable in the `Dockerfile` with a default value of true.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>start-selenium-standalone.sh</strong><dd><code>Add reject unsupported capabilities parameter to Java execution</code></dd></summary>
<hr>

Standalone/start-selenium-standalone.sh

<li>Added <code>--reject-unsupported-caps</code> parameter to the Java command <br>execution.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2341/files#diff-bf348b8b097c88fc4de17029973206ddd04d9c29115cd8a9a1941eb4cd4cc8d9">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Add SE_REJECT_UNSUPPORTED_CAPS environment variable</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Standalone/Dockerfile

<li>Added <code>SE_REJECT_UNSUPPORTED_CAPS</code> environment variable with a default <br>value of true.<br>

</details>

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2341/files#diff-92b52c94ed16b9270e1fcbbf2765768aeb5dfea795374f774977d8717f119a42">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by joerg1985** [comment]
@diemol why not for all standalone servers in https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/commands/DefaultStandaloneConfig.java ?

**Comment by diemol** [comment]
It seems I need to check the tests to make them resilient for this change. I don't have time for this now, so I will close this and circle back later.

**Comment by VietND96** [comment]
@diemol , `SE_REJECT_UNSUPPORTED_CAPS` represents for `--reject-unsupported-caps` is already added to Hub, Distributor and Standadone - https://github.com/SeleniumHQ/docker-selenium/pull/2127/files. However, it is not enforce `true` by default, since it follows default in CLI - https://www.selenium.dev/documentation/grid/configuration/cli_options/
Do we need to enforce to `true` in docker-selenium ?

**Comment by diemol** [comment]
I forgot about that 😆 

We should have it `true` on the standalone ones.

**Pull request closed without merging**
