### PR TITLE
move the creation of the config.json file into a RUN directive

### PR DESCRIPTION
**Pull request by ddavison**
You would *think* that this is a no-op, but it's not.  This was actually creating an issue when running Docker containers in succession with Kubernetes and OpenShift.

This change won't affect other users using this without Kubernetes and OpenShift.  Due to the nature that some Docker containers won't be safe - OpenShift enforces a policy of an [arbitrary user ID](https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html) that has sudo'ers rather than running as root.

### CODE REVIEW

**Comment by ddavison** [comment]
weird.. ^  I'll look into the failure.  worked fine for me earlier.

**Comment by ddavison** [comment]
looks like an issue with circleci, and not able to write to /opt/selenium properly ?  I have a completely identical repository:

`$ docker pull ddavison/docker-selenium-ephemeral` which just contains the changes above, and works just fine locally.

**Comment by ddavison** [comment]
docker committers, could somebody help me with this? :sweat_smile:

**Comment by ddavison** [comment]
poke, docker committers

**Comment by elgalu** [comment]
This looks wrong, taking it away from the `entry_point.sh` will prevent users to change the config at run time.

**Comment by ddavison** [comment]
line 22 chowns the file to seluser, so users will be able to change the config at run time

**Comment by elgalu** [comment]
Sorry, took a slight look and seems I wrote some none-sense.

**Comment by ddavison** [comment]
i wouldn't mind merging this guys, but i wasn't involved with the circleci stuff.  it looks like our CI is broken for this project

**Comment by gerich-home** [comment]
Agree with @elgalu 

Due to this change I am not able to change the value of config options in docker-compose file:
```
  hub:
    image: selenium/hub
    environment:
      - GRID_TIMEOUT=36000
```

I see that my change has no effect (it is critical!).

I try ssh'ing into container:
```
docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS
                             NAMES
...
357362562d6f        selenium/hub                  "/opt/bin/entry_point"   About a minute ago   Up About a minute   4444/tcp
                             e2e_hub_1
...

docker exec -it 357362562d6f sh
```

There I view config.json and see that it has default content in it!
```
$ cat /opt/selenium/config.json

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
```

I try regenerating it manually:
```
$ /opt/selenium/generate_config > /opt/selenium/config.json
```

And it now contains valid values:
```
$ cat /opt/selenium/config.json

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 36000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
```

I vote reverting the change as it broke the ability to configure hub!

**Comment by ddavison** [comment]
looking into it

**Pull request merged**
