### PR TITLE
FROM field in each Dockerfile version specific

### PR DESCRIPTION
**Pull request by rubytester**
Fixes Issue #1

### CODE REVIEW

**Comment by rubytester** [comment]
I would appreciate some feedback on this proposed fix. Thanks.

I see the failure in https://circleci.com/gh/SeleniumHQ/docker-selenium/26 is this:

```
http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar:
2015-06-09 23:09:19 ERROR 503: Service Unavailable.
```

**Comment by mtscout6** [comment]
So the idea is that when it's time for a version bump you will regenerate all the Docerfiles and commit them? Sounds good to me, that will play well with the docker builds!

**Comment by rubytester** [comment]
I can add a `generate_all` target that will change all Dockerfiles apart from generate_x being called before each docker build. This will just change Dockerfiles and you don't have to run docker build on your local machine for all 11 images. 

one more commit then. 


ok, one more commmit with this: 

generate_all

**Comment by kayabendroth-epages** [comment]
+1

**Pull request merged**
