### PR TITLE
Upgrade FF to 46.0.1

### PR DESCRIPTION
**Pull request by Skool**

### CODE REVIEW

**Comment by Skool** [comment]
Looks that it's the Chrome test who failed.

`[chrome]  > CALL init({"browserName":"chrome"}) `
`[chrome]  > POST /session {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"platform":"ANY"}}`
`[chrome]  > CALL get("https://www.wikipedia.org/") `
`[chrome]  > POST /session/url {"url":"https://www.wikipedia.org/"}`
`[chrome]  > CALL title() `
`[chrome]  > GET /session/title `

`{"message":"[title()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'\nSystem info: host: '4b324fe00c2e', ip: '172.17.0.52', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-86-generic', java.version: '1.8.0_91'\nDriver info: driver.version: unknown","status":13,"cause":{"state":"unhandled error","sessionId":"title","hCode":9165882...`

`[chrome]  > CALL quit() `
`[chrome]  > DELETE /session `

**Comment by kayabendroth** [comment]
New Fx version may require a Selenium upgrade.

**Comment by Skool** [comment]
But in our selenium tests, we got more problems with 45.0.2 than with 46.0.1. 
In our selenium grid, we uses the last FF version, it's better than with the 45.0.2.

The tests says that there is a problem with the Chrome node, but i didn't changed it. How can we test what's the best version for Selenium ?

**Comment by ddavison** [comment]
we are up to 47.0.1 now

**Pull request closed without merging**
