### PR TITLE
Fix healthcheck endpoints

### LINKED ISSUE #1529: [🐛 Bug]: HelmChart should use /readyz endpoint to check the health - so that k8s can restart a failed grid
### What happened?

The Http statuscodes for the /readyz endpoint have been adjusted (https://github.com/SeleniumHQ/selenium/issues/10391). The status endpoint as you can see in the Selenium ticket returns always 200 - Ok even if the grid isn't running properly.

We should adjust the helmchart to use the readyz endpoint for health checks. So that kubernetes can restart the grid on it's own.

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/chart/selenium-grid/values.yaml#L199

### Command used to start Selenium Grid with Docker

```shell
Helm deployment
```

### Relevant log output

```shell
non
```

### Operating System

Linux

### Docker Selenium version (tag)

Latest helm chart

### PR DESCRIPTION
**Pull request by ilpianista**
### Description

Fixes #1529

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by diemol — APPROVED** [review]
Thank you, @ilpianista!

**Comment by kmcrawford** [comment]
I have a router that is not responding but the `/readyz` is still returning a 200 and thus not restarting to fix the issue.

image

Below is the most common exception in the logs: (I have hours of logs in `FINE` mode if needed)
`Expected to read a START_MAP but instead have: END`

**Comment by diemol** [comment]
I think I asked in the other issue if it was possible to see the full stacktrace of the error.

**Comment by kmcrawford** [comment]
@diemol There is no smoking gun in the logs, and there is a limit in Github for me to post the logs.  Can I send you the logs another method?

**Comment by diemol** [comment]
OK, seems you are having this issue #1507 and probably this one too #1605

**Pull request merged**
