### PR TITLE
adding chart ingress namespace field

### PR DESCRIPTION
**Pull request by IronMage**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Selenium Grid chart does not include the release namespace in the object definition, causing it to be deployed to the default namespace rather than the target namespace.

### Motivation and Context
Deploying with the `helm --namespace` flag causes the ingress to potentially be deployed to a different namespace.

### Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
@IronMage could you please sign the CLA?

**Comment by IronMage** [comment]
> @IronMage could you please sign the CLA?

This has been signed. Could've been an issue with an email missing; that has been fixed.

**Comment by diemol** [comment]
Your commit does not have the email associated.

**Comment by IronMage** [comment]
@diemol See #1966 instead.

**Pull request closed without merging**
