### PR TITLE
Adds build steps in makefile for building Chrome and Firefox betas

### LINKED ISSUE #1286: Beta and dev versions in Docker Hub
## 🚀 Feature Proposal

It would be amazing if we could pull the official selenium-docker images for the beta and development versions of the major browsers (i.e., Chrome, Firefox, and Edge) from Docker Hub. It would be also great if we could have a new tag for the current stable version.

## Motivation

For many companies, it is key to have the possibility of checking if a web application continues working as expected in the next stable release. This process can be tricky, but it can be easily done with Docker containers. Companies like [Twilio](https://hub.docker.com/r/twilio/selenoid) are already maintaining similar Docker images.

## Example

Currently, we can pull a given version of the major browsers as follows:

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:90.0
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:91:0
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-edge:88.0
```

My proposal requires to include and maintain new tags: `stable`, `beta` (typically stable+1), and `dev` (typically stable+2):

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:stable
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:stable
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-edge:stable
```

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:beta
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:beta
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-edge:beta
```

```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:dev
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:dev
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-edge:dev
```

### PR DESCRIPTION
**Pull request by jamesmortensen**
Build steps to build Chrome Beta and Firefox Beta nodes and standalone from the makefile.  Fixes #1286 

### Description

When running `make build`, all of the images will be built, including four more additional images:

- node-chrome beta
- node-firefox beta
- standalone-chrome beta
- standalone-firefox beta

Beta images can also be built using `make chrome_beta` and `make standalone_chrome_beta` and so forth.

The tag '-beta' is added to the end of the build date.  For instance, selenium/node-chrome:20220815-beta

### Motivation and Context

Some community members want to run tests on up and coming versions of these browsers so they can be more informed when a change in the browser code may affect their application.  This first step makes it easier for users to build the images themselves and paves the way for these images to be deployed to Docker Hub via the CI pipeline.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

I've marked this as a draft PR as more work needs to be done to complete it.

### CODE REVIEW

**Comment by jamesmortensen** [comment]
I also marked this as a draft pull request since it will be easier to merge https://github.com/SeleniumHQ/docker-selenium/pull/1656 before making the full set of changes for automatically building Chrome and Firefox betas...

**Comment by jamesmortensen** [comment]
Here is a test release that shows what the release notes might look like.  https://github.com/jamesmortensen/docker-selenium/releases/tag/4.4.0-20220816.  I limited the beta tag to only being placed on the 4.4.0-20220816-beta "grid and build date" tag.  Also, the release notes include the hash from Docker Hub as well.

Please let me know if there's any changes needed to the release notes or tags, and I'll move the necessary from the "test-beta-deploy" branch to the PR branch.  (Some modifications to perform the test as "jamesmortensen1" need to be removed prior to merging this.)

**Comment by jamesmortensen** [comment]
fixes #1286

**Comment by jamesmortensen** [comment]
I just realized the docs may need to be updated.  Just FYI.

**Review by diemol — APPROVED** [review]
Thank you, @jamesmortensen! This is great! 

We can have a separate PR for the README to briefly document the existence of these images.

**Pull request merged**
