### PR TITLE
upgrade to 3.3.1

### PR DESCRIPTION
**Pull request by manoj9788**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ddavison** [comment]
i'll need to release 3.2 and 3.3.0 before we release 3.3.1.   will get to this.

**Comment by manoj9788** [comment]
@pavelpp 3.2 was just released 4 days ago, so I assume we will have to wait for few more days.

**Comment by ddavison** [comment]
yea - i've got some catching up to do.  was dealing with some personal stuff recently :) will release it today

**Comment by ddavison** [comment]
this was merged in a while back

**Pull request closed without merging**
