### PR TITLE
Added JAVA_OPTS environment variable to control java process.

### PR DESCRIPTION
**Pull request by ipreachable**
#40

### CODE REVIEW

**Comment by kayabendroth-epages** [comment]
+1

**Comment by willroden** [comment]
@ipreachable, Have you [signed the CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) as described in [CONTRIBUTING.md](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md)?  If not, please sign it so that we can merge this.

Also, it would be helpful to add some documentation about where to specify JAVA_OPTS.

**Comment by ipreachable** [comment]
I have signed CLA.

**Comment by rubytester** [comment]
Hi @ipreachable I would like to merge this: 

My request: 
- please rebase on master to pickup `Standalone` images added since original PR. 
- Add JAVA_OPTS to Standalone
- Addition to README on usage would be nice.

Thanks.

**Comment by rasmusbergpalm** [comment]
Any news on this?

**Comment by rubytester** [comment]
I'll work on this today. Just realized I need this to experiment with `-Xmx1024m` value on a large grid so JAVA_OPTS would be quite useful. 

I'll rebase and add JAVA_OPTS to standalone.

**Pull request merged**
