### PR TITLE
Removed copy command from debug image

### PR DESCRIPTION
**Pull request by ersuniljoshi**
- [ X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ddavison** [comment]
what's the reason for this change?  this piece is needed.  additionally - in the line below the one you took out, there would be a failure since you can't chmod a file that doesn't exist ;)

**Comment by ersuniljoshi** [comment]
@ddavison the reason I have removed this file is, its already being copied in the above docker image(i.e. StandaloneFireFox) and this copy will fail as "entry_point.sh" doesnot even exists in the folder named "StandaloneFireFoxDebug". After removing this file I was able to build the debug image. Otherwise its fails with Error "No such file or directory"

**Comment by ddavison** [comment]
hey! good call - let me take a closer look

**Comment by diemol** [comment]
@ersuniljoshi but this is needed, even if the base image has an entry_point.sh, those Dockerfiles overwrite it because the debug one has VNC running.

This change does not apply. I'll close this PR.

**Pull request closed without merging**
