### PR TITLE
helm: add ingress for router/hub

### PR DESCRIPTION
**Pull request by nefelim4ag**
### Description
Allow publish router/hub UI via ingress

### Motivation and Context
While development process i want give a sight for automation team what happens inside

### Types of changes
- [X] New feature (non-breaking change which adds functionality)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nefelim4ag** [comment]
IIRC
From our internal experience when we first tried running grid on k8s with our own charts, this chart missing some things and I at least will try to add some things here:
* PDB for main components
* Scaling for nodes, I'm not sure about does it reasonable to add our auto scaler, but I personally preffer to add keda.sh object if that is acceptable.
```
          apt update;
          apt -qq install -y curl jq;
          KUBECTL_VER=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt); \
          curl -SL "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VER}/bin/linux/amd64/kubectl" -o /usr/bin/kubectl; \
          chmod +x /usr/bin/kubectl;

          echo "### Run autoscaler";
          LAST=0
          while :; do
            QUEUE=$(curl -s http://selenium-hub:4444/se/grid/newsessionqueuer/queue | jq ".[] | length");
            SESSIONS=$(curl -s http://selenium-hub:4444/status | jq -c '.value.nodes[].slots[].session' | grep -cv 'null');
            SUM=$((QUEUE + SESSIONS));
            if ((LAST != SUM)); then
              echo "Scale: $LAST -> $SUM";
              kubectl scale deployment selenium-node-chrome --replicas=${SUM} && LAST=$SUM;
            fi

            sleep 15;
          done;
```
* lifecycle prestop hooks for browser nodes like:
```
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    curl -X POST ${POD_IP}:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
                    while curl ${POD_IP}:5555/status; do sleep 1; done
```

**Comment by lorantalas** [comment]
Seems to be a duplicate of #1562. Issue #1546 is closed.
@Nefelim4ag you may just switch to chart version [0.4.0](https://github.com/SeleniumHQ/docker-selenium/releases/tag/selenium-grid-0.4.0)

**Comment by den-is** [comment]
That is a duplicate of already submitted and then merged PR https://github.com/SeleniumHQ/docker-selenium/pull/1562

**Comment by diemol** [comment]
Thanks for pointing it out, @lorantalas!

**Pull request closed without merging**
