### PR TITLE
Bumping to 4.7.2

### PR DESCRIPTION
**Pull request by ghost**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Bumping to Selenium Grid 4.7.2

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Seems the build is failing because of the coursier download and execution https://github.com/SeleniumHQ/docker-selenium/actions/runs/3702914588/jobs/6274019397#step:9:1071 

@krmahadevan @Xcalizorz do you have time to have a look?

**Comment by krmahadevan** [comment]
> Seems the build is failing because of the coursier download and execution https://github.com/SeleniumHQ/docker-selenium/actions/runs/3702914588/jobs/6274019397#step:9:1071
> 
> @krmahadevan @Xcalizorz do you have time to have a look?

@diemol - I am seeing this error

```
/tmp/cs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/cs)
```

I went back to the coursiers repo and noticed that there was a change done https://github.com/coursier/launchers/commit/60da306b6702ee91de281cb6e6ec959324449b3f

Not sure if that would be the cause. I dont have a UNIX machine to try this out and confirm this theory

**Comment by ghost** [comment]
> > Seems the build is failing because of the coursier download and execution https://github.com/SeleniumHQ/docker-selenium/actions/runs/3702914588/jobs/6274019397#step:9:1071
> > @krmahadevan @Xcalizorz do you have time to have a look?
> 
> @diemol - I am seeing this error
> 
> ```
> /tmp/cs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/cs)
> ```
> 
> I went back to the coursiers repo and noticed that there was a change done [coursier/launchers@60da306](https://github.com/coursier/launchers/commit/60da306b6702ee91de281cb6e6ec959324449b3f)
> 
> Not sure if that would be the cause. I dont have a UNIX machine to try this out and confirm this theory

It looks like coursier was built using glibc `2.32` and the image has an older version:

```
root@xcalizorz:/# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

It seems that Ubuntu `focal` repositories do not have glibc `2.32`, yet:

```
root@xcalizorz:/# apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.31-0ubuntu9.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I would not recommend updating glibc manually (building, etc. needed) since it is a very central library and we should use the one shipped with ubuntu. 

`ubuntu:focal` provides glibc `2.31`; so we need to update to a newer ubuntu version.

The latest LTS for ubuntu would be `jammy` with glibc `2.35`. I have some issues building the image, when all tests pass locally, we can try updating the version of ubuntu. What do you think?

**Comment by ghost** [comment]
Using `jammy` was unsuccessful (same error, because glibc 2.35 != 2.32 😢)

Currently, the only quick solution would be to use the [JAR based coursier](https://get-coursier.io/docs/cli-installation#linux-macos) launcher instead of using the native one (see my latest commit).

**Review by diemol — APPROVED** [review]
Thank you, @Xcalizorz!

**Pull request merged**
