### PR TITLE
README styling and readability updates.

### PR DESCRIPTION
**Pull request by meeroslaph**

### CODE REVIEW

**Comment by rubytester** [comment]
Thank you. Would you kindly review and see if there are other typos or inaccuracies, it would be nice to have another pair of eyes to review for clarity, completeness and any out of dateness stuff.

**Comment by meeroslaph** [comment]
Sure! That is something I was thinking about. I will enhance some references with appropriate URLs and review overall readability. Will keep you updated in this.

**Comment by meeroslaph** [comment]
I have updated README.md file ([preview rendered version with the updates](https://github.com/meeroslaph/docker-selenium/blob/patch-1/README.md)) with styling and readability improvements. Also license files inside each folder with dockerfiles were updated to have a link to the [LICENSE.md](https://github.com/meeroslaph/docker-selenium/blob/patch-1/LICENSE.md) file instead of the old link referencing the file located in Google Code.

Hope this was helpful!

**Comment by rubytester** [comment]
Thank you so much. 

Sorry for the delay responding. I wonder why the tests failed. This is not a code change.

**Comment by elgalu** [comment]
It says `7:31:10 waiting for builds to finish` but no logs, maybe TravisCI works better?

**Comment by rubytester** [comment]
Could you also squash the commits to make it one logical commit to be merged? 

Something like `git rebase -i master` and then rework the first commit with all comments and squash the rest into it.  

I hope I am not being too unreasonable and pedantic on this.

**Comment by meeroslaph** [comment]
@rubytester Done! Thank you for rebase + squash usage suggestion.

p.s.: The reason of failed tests on my previous commits is unclear for me as well. Luckily, with the only one commit everything has worked out. Thanks again!

**Comment by rubytester** [comment]
Some housekeeping: Have you [signed the CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) as described in [CONTRIBUTING.md](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md)?

Please indicate here. Thanks and we'll merge it.

**Comment by meeroslaph** [comment]
I have just made myself familiar with this document and signed the CLA. Thanks for pointing this out.

**Pull request merged**
