### PR TITLE
[feat][test]: add env vars to generate config for Relay in node-base

### PR DESCRIPTION
**Pull request by VietND96**
### **User description**

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
[feat][test]: add env vars to generate config for Relay in node-base

### Motivation and Context
---
### Node configuration relay commands

Relaying commands to a service endpoint that supports WebDriver.
It is useful to connect an external service that supports WebDriver to Selenium Grid. An example of such service could be a cloud provider or an Appium server. 
In this way, Grid can enable more coverage to platforms and versions not present locally.

The following is an en example of connecting an Appium server to Grid.

[docker-compose-v3-relay.yml](https://github.com/SeleniumHQ/docker-selenium/blob/95e3b54b7e15e929c1cf35ce1ec0a749c84e0164/docker-compose-v3-relay.yml)

If you want to relay commands only, `selenium/node-base` is suitable and lightweight for this purpose.
In case you want to configure node with both browsers and relay commands, `selenium/node-chrome` or `selenium/node-docker` (with TOML configuration options) can be used.

To run a sample test with the relayed node, you can clone the project and try below command:

```bash
make test_node_relay
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

___

### **PR Type**
enhancement, tests

___

### **Description**
- Introduced environment variables and conditional logic for node relay testing in Python tests.
- Updated GitHub Actions workflows by adding node relay tests and removing scheduled cron jobs.
- Added new Makefile targets and Docker Compose configurations to support node relay testing.
- Enhanced node configuration scripts to include relay options and updated documentation accordingly.
- Created a new Dockerfile for an Android testing environment.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>4 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add Environment Variables and Conditional Delay for Node Relay</code></dd></summary>
<hr>
      
tests/SeleniumTests/__init__.py

<li>Added environment variables for node relay and Android platform API.<br> <li> Introduced a conditional delay when <code>TEST_NODE_RELAY</code> is not 'false'.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-9e40695776a7c3afc35b1bf6d31682fe8ca531271c4a883063aa428b3915387f">+13/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Makefile</strong><dd><code>Introduce Make Targets for Node Relay Testing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
Makefile

- Added new make targets for testing node relay configurations.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52">+25/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>generate_config</strong><dd><code>Enhance Node Configuration Script with Relay Options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
NodeBase/generate_config

<li>Added relay configuration blocks to the node configuration script.<br> <li> Adjusted node stereotype and driver configuration settings.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-7588f975550d93b98a8db2d5aa40b89c714b125a6bc81ea550556b1bca556f52">+49/-12</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile.android</strong><dd><code>Create Dockerfile for Android Testing Environment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/Dockerfile.android

<li>Added a new Dockerfile for building an Android-based testing <br>environment.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-e0e2b4bfaae3155b8345535d93b8fe501152f9d0d6be1346ea66bae51272d074">+13/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes
</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>docker-test.yml</strong><dd><code>Update GitHub Actions for Docker Tests with Node Relay</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
.github/workflows/docker-test.yml

<li>Removed scheduled cron jobs.<br> <li> Added a new test strategy for node relay with corresponding setup <br>steps.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-baa08c0b7cb0ae6357ecf7ecaa2d7aff0bfa417e10e1ec6fbc29232cb0166da7">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>helm-chart-test.yml</strong><dd><code>Remove Scheduled Cron Jobs from Helm Chart Tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
.github/workflows/helm-chart-test.yml

- Removed scheduled cron jobs.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-4a8a322b12899fb1d6c3c11d85f3f42b3486d64a25e6a3cd20e521bc94140897">+0/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nightly.yaml</strong><dd><code>Update Nightly Workflow to Conditionally Include Tests</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
.github/workflows/nightly.yaml

<li>Added conditional execution for docker and helm chart tests based on <br>event triggers.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-e79198339eb3fcc6974b6912e52526068eab3b7952ed67d03276479a235eb58e">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>docker-compose-v3-relay.yml</strong><dd><code>Add Docker Compose Configuration for Node Relay</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docker-compose-v3-relay.yml

<li>Created a new Docker Compose file for setting up environments with <br>node relay.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-f377705512ffd3f5916956e0d655fc17cce188234fcc5845657043403925ba70">+66/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>docker-compose-v3-test-node-relay.yml</strong><dd><code>Setup Docker Compose for Node Relay Testing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/docker-compose-v3-test-node-relay.yml

- Introduced a Docker Compose configuration for node relay testing.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-696f51c969c021fb13a49475ca5b17b73d90e71a2f04a206fee75e91097d0f50">+94/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Document Node Configuration Relay Commands</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
README.md

- Added documentation for node configuration relay commands.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/docker-selenium/pull/2254/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+19/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thank you for doing this, @VietND96.

Offering a way to configure Relay is a good idea, but the PR adds too much complexity to the project. Let me explain:
- We already have too many environment variables and need to document them all at some point. We recommend to use `config.toml` files to configure the Grid, so I prefer to offer a way to the user to mount it and use it for Relay. It is easier to read a file instead of several environment variables.
- I know Relay is a common way to integrate Appium. However, the tests in this PR are hard to maintain, and the Android image is know to work slowly when nested virtualization is not present. If we want to test this, I prefer to start a Standalone container, and have it as the receiver of the forwarded commands through Relay.

**Comment by VietND96** [comment]
@diemol, I see `--config` can pass multiple toml files. Can we separate another `generate_relay_config` and isolate related env vars there? Of course, still many env vars, but it is readable. Because there were few env vars with default values get/set. A toml config file can be defined and mounted to the container, however it needs to rewrite all without reusable existing. Separate out another toml file for relay I think it would help in case we want to mount specific relay configs within reuse existing default node configs.

**Comment by diemol** [comment]
It is a good idea to have it as a different file. But I still dislike the environment variables approach; for example, setting the stereotypes via environment variables makes it very hard to read and maintain.

**Comment by VietND96** [comment]
@diemol, few changes have been done
- I don't add the env var for setting complex stereotypes to balance both approaches. Env vars are used for basic config to be generated. For complex stereotypes, let the user disable generate config mode and input a TOML config file.
- Add a test with `start a Standalone container, and have it as the receiver of the forwarded commands through Relay`.
- I would like to keep a test for the node relay to Appium (for reason like a reference test to verify & confirm something works quickly) . If the test is not stable or hard to maintain later, simplify to remove `Android` from the for loop in Makefile :)

**Review by diemol — APPROVED** [review]

**Pull request merged**
