### PR TITLE
Faster access to noVNC

### PR DESCRIPTION
**Pull request by nwtgck**
Thank you so much for the wonderful project!

I slightly changed the README.

Access to <http://localhost:7900/?autoconnect=1&password=secret> is faster without typing the password and clicking the button.

## Demo
https://user-images.githubusercontent.com/10933561/208279333-33858000-8b31-4747-9565-95c80398e146.mp4

## noVNC document

The query parameter is documented on noVNC.
image

https://github.com/novnc/noVNC/blob/4fb2d6c497dc2e307400ff581f9292758c709b40/docs/EMBEDDING.md?plain=1#L31-L48

---

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Motivation and Context

To improve user experience for document users.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nwtgck** [comment]
I would like to add `&resize=scale` because I always set "Local Scaling" in the Scaling Mode setting.

Could I change this in the PR?

**Comment by diemol** [comment]
> I would like to add `&resize=scale` because I always set "Local Scaling" in the Scaling Mode setting.
> 
> Could I change this in the PR?

Sure. Please also sign the CLA so we can merge this.

**Comment by nwtgck** [comment]
I added it and signed.

**Review by diemol — APPROVED** [review]
Thank you, @nwtgck!

**Pull request merged**
