### PR TITLE
Add Chinese fonts for #339 #367

### PR DESCRIPTION
**Pull request by omz-one**
Add Chinese fonts ttf-wqy-microhei and ttf-wqy-zenhei

- [X ] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by omz-one** [comment]
img

**Comment by diemol** [comment]
He @omz-one,

Thanks for this PR! Did you check how much bigger the image gets?

**Comment by diemol** [comment]
Hi @omz-one,

Could you check my comment? In addition, why is the change made on the Base dockerfile? Shouldn't it be done on the NodeBase dockerfile?

**Comment by diemol** [comment]
OK, so the images grow around ~25MB, which is ok I think, considering that a bigger user base will be able to render websites that use this character set.

We'll merge it but then move the two fonts to the NodeBase dockerfile.

**Comment by diemol** [comment]
Before:
before
After:
after

**Pull request merged**
