### PR TITLE
Switching to Jammy

### PR DESCRIPTION
**Pull request by diemol**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
Firefox tests are failing because the current way of installing Firefox is not working on 22.04. Firefox is a snap package in Ubuntu 22.04, and we need to figure out how to remove it, install the deb package, use the snap package, and allow beta/dev versions to be installed.

**Comment by amardeep2006** [comment]
@diemol  I just came across this Article to install Nightly. 

https://www.omgubuntu.co.uk/2023/10/firefox-nightly-deb-packages-mozilla-apt-repostiory

https://blog.nightly.mozilla.org/2023/10/30/introducing-mozillas-firefox-nightly-deb-packages-for-debian-based-linux-distributions/

Does this means they have plans to do the same for other channels as well ? Or may be I am interpreting it too much ?? 
image

**Comment by diemol** [comment]
> @diemol I just came across this Article to install Nightly.
> 
> https://www.omgubuntu.co.uk/2023/10/firefox-nightly-deb-packages-mozilla-apt-repostiory
> 
> https://blog.nightly.mozilla.org/2023/10/30/introducing-mozillas-firefox-nightly-deb-packages-for-debian-based-linux-distributions/
> 
> Does this means they have plans to do the same for other channels as well ? Or may be I am interpreting it too much ?? image

Seems so. The problem is that Firefox comes installed as a snap package in Jammy, so we also need a way to "remove" that binary before installing the one we want.

**Comment by VietND96** [comment]
I tried to troubleshoot and saw there are 2 errors in the Firefox node when starting Firefox browser
```
XPCOMGlueLoad error for file /opt/firefox-latest/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load
```
```
XPCOMGlueLoad error for file /opt/firefox-119.0.1/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM
```
I have updated Dockerfile to `apt-get install` these 2 packages `libgtk-3-dev`, `libdbus-glib-1-dev`
All tests could be seen passed in the workflow https://github.com/ndviet/docker-selenium/actions/runs/6820672426
The update comes to feature branch via #2001

**Comment by diemol** [comment]
Thanks for your help @vietnd96!

**Pull request merged**
