### PR TITLE
Updated geckodriver to latest version 0.17.0

### PR DESCRIPTION
**Pull request by testphreak**

### CODE REVIEW

**Comment by ddavison** [comment]
hey @testphreak , you neglected to provide the template that was in there by default.  
have you signed the [CLA](https://goo.gl/a2VrTx)?

**Comment by testphreak** [comment]
Hi @ddavison, I did sign the CLA last time with a previous commit. I used GitHub Desktop to create the pull request this time instead of the GitHub Web, perhaps that's the reason why I didn't get the CLA.

**Comment by ddavison** [comment]
must be, yea.  If you signed the CLA, then i'm good with it :)

**Comment by ddavison** [comment]
thanks for this!

**Comment by testphreak** [comment]
thanks for the merge @ddavison!

**Pull request merged**
