### PR TITLE
Upgrade Selenium to version 2.49.1.

### PR DESCRIPTION
**Pull request by kayabendroth**

### CODE REVIEW

**Comment by bbarke** [comment]
Should this wait until https://github.com/SeleniumHQ/selenium/issues/1495 is resolved before merging?

**Comment by kayabendroth** [comment]
@bbarke Good idea as the issue seems to be a regression introduced in 2.49.0.

**Comment by kayabendroth** [comment]
@rubytester Let's wait for 2.49.1 before merging.

**Comment by davehunt** [comment]
2.50 is now out.

**Comment by rubytester** [comment]
Hi, do we want 2.49.1 or do we skip it and go directly for 2.50?

**Comment by kayabendroth** [comment]
@davehunt, @rubytester I'd suggest to wait a few days to see, if there are regressions in 2.50.

**Comment by rubytester** [comment]
Yes, so I decided to merge and keep building images for both 2.49.1 and for 2.50.0

**Pull request merged**
