### PR TITLE
Chrome proxy support

### PR DESCRIPTION
**Pull request by ageekymonk**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

Added support for providing proxy to the node chrome.

### CODE REVIEW

**Comment by diemol** [comment]
Hi @ageekymonk,

Thanks for submitting this PR. Nevertheless, could you please provide more context? Isn't it just necessary to add the `-e proxy_host=proxy.example.com -e proxy_port=8080 -e no_proxy=localhost,*.dev.example.com` to the `docker run...` command? Why is it necessary to change the Chrome start command?

**Comment by ageekymonk** [comment]
Thanks @diemol. In enterprise, there are proxy to reach external websites, so we need proxy settings to be in chrome to test.

**Comment by diemol** [comment]
I understand the issue with proxies used in companies, I just would like to understand why the flags `-e proxy_host=proxy.example.com -e proxy_port=8080 -e no_proxy=localhost,*.dev.example.com` are not enough.

**Comment by ageekymonk** [comment]
@diemol sorry, i did not understand you earlier. google chrome does not pick the proxy from the environment, it needs to be passed explicitly. 
This has been reported earlier as well https://github.com/SeleniumHQ/docker-selenium/issues/78 and it is still the same.

**Comment by diemol** [comment]
I checked again and I can see that Chrome using the proxy env var, please follow this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/537#issuecomment-414789754).

**Pull request closed without merging**
