### PR TITLE
README improvements and fixes

### PR DESCRIPTION
**Pull request by ay0o**
Issue #799 was partially caused by a missing port in the docker run
statement

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md#contributing-code-to-selenium)

### CODE REVIEW

**Comment by ay0o** [comment]
FYI, CI is failing due to an unrelated error.

**Comment by diemol** [comment]
Hi @ay0o,

Thanks for the PR. Could you also please add instructions showing to to start Docker Swarm?

**Comment by ay0o** [comment]
@diemol updated it, but I think that's out of the scope of docker-selenium.

**Comment by diemol** [comment]
Thanks for your contribution!

**Pull request merged**
