### PR TITLE
docker image for a hub with prioritizer

### PR DESCRIPTION
**Pull request by roydekleijn**
This customized hub allows you to prioritize tests with a DesiredCapability.
Eg: `caps.setCapability("_important", true);` 

Important test = `caps.setCapability("_important", true); `

Less important test = `caps.setCapability("_important", false); `

### CODE REVIEW

**Comment by elgalu** [comment]
So you just dropped a binary `HubPrioritizer/GridPlugin-0.0.1.jar` here :p Where is the source code?

**Comment by roydekleijn** [comment]
you want me to put the mvn project there as well ? (inside: HubPrioritizer/
)

On Thu, Jun 2, 2016 at 6:09 PM, Leo Gallucci <notifications@github.com>
wrote:

> So you just dropped a binary HubPrioritizer/GridPlugin-0.0.1.jar here :p
> Where is the source code?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SeleniumHQ/docker-selenium/pull/231#issuecomment-223340559>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPP1X4nbUj32_JrGjib8XRmUoYiP6Vrks5qHwA1gaJpZM4IssSW>
> .
>



-- 


[image: --]
Roy de Kleijn
[image: http://]about.me/roydekleijn
<http://about.me/roydekleijn?promo=email_sig>

**Comment by elgalu** [comment]
Hehe, perhaps it would be better to leave the mvn project in another repo and clone it here, putting a binary implies security concerns.

**Comment by roydekleijn** [comment]
ok, good suggestion, will push it shortly

**Comment by roydekleijn** [comment]
binary removed from repo...

**Comment by roydekleijn** [comment]
What kind of additional steps I have to follow, before my pull request will be merged

**Comment by ddavison** [comment]
not sure i like the idea of having something like this in our repo.. if this is put in, then other "grid enhancement" libraries will be put in.  as far as i can tell, this is just allowing people to prioritize tests.  I think i'd prefer leaving this out.  that being said - it's easy to create and push your own docker images to hub.docker.com !

sorry, @roydekleijn.  for any future pull requests you may submit, could you please fix your `git config --global user.name` and `git config --global user.email`?  your commits are showing up as an unknown author.  also verify that you've signed the [CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0)

**Comment by roydekleijn** [comment]
Ok, at least we have some clarity now. Will put it in my fork of
docker-selenium.

Op 2 okt. 2016 10:06 a.m. schreef "Dj" <notifications@github.com>:

**Pull request closed without merging**
