### PR TITLE
Standalone Debug dockerfiles for firefox and chrome

### PR DESCRIPTION
**Pull request by rubytester**
- Adding `StandaloneDebug` folder similar to `NodeDebug` but operating on a Standalone Selenium mode.
- Generating `StandaloneDebugChrome` and `StandaloneDebugFirefox` folders from templates
- resulting in docker images `selenium/standalone-chrome-debug` and `selenium/standalone-firefox-debug`

(I have signed CLA in previous contribution to selenium unless I need to sing it again.)

Please let me know if I missed something. 

Thank you.

### CODE REVIEW

**Comment by willroden** [comment]
This will be a big help.

**Comment by mattjbray** [comment]
FYI, on a linux host, you can get visual debugging using the existing standalone images:
```
docker run -it --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           selenium/standalone-firefox \
           java -jar /opt/selenium/selenium-server-standalone.jar
```

I think you'd still need the VNC solution on a Mac though.

**Comment by rubytester** [comment]
Rebased, pulled in CircleCi change into the branch. Awaiting happy green check marks and I will merge this enhancement

**Comment by pataquets** [comment]
Making them also available as Docker Hub images would be great.

**Comment by rubytester** [comment]
you are correct, I just realized that docker hub image does not just magically do it and action...

**Pull request merged**
