### PR TITLE
Add a RUN step to install freshplayerplugin - Flash Player for Firefox

### PR DESCRIPTION
**Pull request by echernyavskiy**

### CODE REVIEW

**Comment by rubytester** [comment]
We use Firefox without flash. Firefox complains that flash plugin is not installed but this has not caused any functional testing issues for us.  I would recommend adding flash in a downstream container.

**Comment by rubytester** [comment]
I assume there is no more tracktion on this pull request and I want to close it and defer plugin installation in a downstream container based on `node-firefox`. Opinions?

**Comment by mtscout6** [comment]
That's fair

**Comment by rubytester** [comment]
spoiled milk at this point, reopen or start a new conversation

**Pull request closed without merging**
