### PR TITLE
Github Workflow to Lint and Test Helm Chart

### PR DESCRIPTION
**Pull request by amardeep2006**
**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
This is related to https://github.com/SeleniumHQ/docker-selenium/issues/1975
1. Added a workflow to lint and test helm charts
2. Added maintainer info in Charts.yml
3. Did one time linting for issues thrown by linter

### Motivation and Context
It will do one basic testing for helm chart by linting and installing in Kubernetes. The advanced testing can be built on top of this.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diemol** [comment]
@amardeep2006 can you please check the commits? One of them is not recognizing your GitHub user.

**Comment by amardeep2006** [comment]
@diemol That is fine , all commits are mine. Probably I messed up git profile in my local machine.

**Comment by diemol** [comment]
I know, but the CLA needs to be signed by the commits owner.

**Comment by diemol** [comment]
image

**Comment by amardeep2006** [comment]
I am closing the PR , not sure how to correct the commits. I will raise again from a new branch with clean commits.

**Pull request closed without merging**
