### PR TITLE
Upgrade Selenium to version 2.47.1.

### PR DESCRIPTION
**Pull request by kayabendroth**

### CODE REVIEW

**Comment by elgalu** [comment]
Actually should be 2.47.1 a fix was sent right after 2.47.0

**Comment by kayabendroth** [comment]
@elgalu I'll change it then. Thanks.

**Comment by rubytester** [comment]
The recommendation for 2.47.1 is now to be on java 8. Should we bump it too?

https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

**Comment by rubytester** [comment]
Thanks @kayabendroth 

Some housekeeping: Have you [signed the CLA](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) as described in [CONTRIBUTING.md](https://github.com/SeleniumHQ/docker-selenium/blob/master/CONTRIBUTING.md)?

Please indicate here. Thanks and we'll merge it.

**Comment by elgalu** [comment]
I think is ok to upgrade to java 8, has being working ok for me for some time now: https://github.com/elgalu/docker-selenium/blob/99ebf86eb7bf6a155c12bb24a5bfa95676c87049/Dockerfile#L125

**Comment by kayabendroth** [comment]
@rubytester +1 for using JRE 8.

I signed the CLA just now.

**Comment by kayabendroth** [comment]
I upgraded the Ubuntu version we use as a base image to 14.10, as 14.04 doesn't have native Java 8 packages. I also tried 15.04, but ran into a timeout problem during ```make test```, which I didn't want to investigate right now. We can upgrade to 15.04 later on.

**Comment by kayabendroth** [comment]
Just saw that Utopic reached it's "end of support"-date already (by the end of July). I'll look into the timeout problem with Vivid. Maybe this PR can be merged anyway?

**Comment by elgalu** [comment]
Yes, I would work on a separate PR to upgrade Java

**Comment by kayabendroth** [comment]
Java update removed from PR as it involves upgrading Ubuntu as well and the upgrade to Vivid doesn't work out-of-the-box, at least not for me testing this on my local machine.

**Comment by rubytester** [comment]
Each image in docker hub https://registry.hub.docker.com/repos/selenium/
now has a tag 2.47.1 pulling from the branch 2.47.1
master branch tag is latest. Both master and 2.47.1 branches point to the same sha1.

Thanks

**Pull request merged**
